import { StaticImport } from "next/dist/shared/lib/get-img-props";
import { ImageRepository } from "../../public/assets/images/ImageRepository";
import { Map, Set } from "immutable";

export enum DisplayableCuisine {
  AMERICAN = "american",
  BAR = "bar",
  BARBIQUE = "barbique",
  CAFE = "cafe",
  CHINESE = "chinese",
  DESSERT = "dessert",
  FRENCH = "french",
  HAMBURGER = "hamburger",
  INDIAN = "indian",
  ITALIAN = "italian",
  JAPANESE = "japanese",
  MEXICAN = "mexican",
  PIZZA = "pizza",
  SEAFOOD = "seafood",
  STEAK = "steak",
  THAI = "thai",
}

export const CUSINE_ICONS = Map<DisplayableCuisine, StaticImport>({
  american: ImageRepository.FoodIcons.AmericanIcon,
  bar: ImageRepository.FoodIcons.BarIcon,
  barbique: ImageRepository.FoodIcons.BarbiqueIcon,
  cafe: ImageRepository.FoodIcons.CafeIcon,
  chinese: ImageRepository.FoodIcons.ChineseIcon,
  dessert: ImageRepository.FoodIcons.DessertIcon,
  french: ImageRepository.FoodIcons.FrenchIcon,
  hamburger: ImageRepository.FoodIcons.HamburgerIcon,
  indian: ImageRepository.FoodIcons.IndianIcon,
  italian: ImageRepository.FoodIcons.ItalianIcon,
  japanese: ImageRepository.FoodIcons.JapaneseIcon,
  mexican: ImageRepository.FoodIcons.MexicanIcon,
  pizza: ImageRepository.FoodIcons.PizzaIcon,
  seafood: ImageRepository.FoodIcons.SeafoodIcon,
  steak: ImageRepository.FoodIcons.SteakIcon,
  thai: ImageRepository.FoodIcons.ThaiIcon,
});

export const CUSINE_EQUIVALENCE = Map<string, Set<DisplayableCuisine>>({
  "do-it-yourself food": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  donairs: Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  friterie: Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  salumerie: Set<DisplayableCuisine>([
    DisplayableCuisine.AMERICAN,
    DisplayableCuisine.ITALIAN,
  ]),
  smokehouse: Set<DisplayableCuisine>([
    DisplayableCuisine.AMERICAN,
    DisplayableCuisine.BARBIQUE,
  ]),
  "american (new)": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  "new american": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  "american (traditional)": Set<DisplayableCuisine>([
    DisplayableCuisine.AMERICAN,
  ]),
  "traditional american": Set<DisplayableCuisine>([
    DisplayableCuisine.AMERICAN,
  ]),
  baguettes: Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  barbeque: Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  "beer garden": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  "beer hall": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  burgers: Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  "cajun/creole": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  cheesesteaks: Set<DisplayableCuisine>([
    DisplayableCuisine.AMERICAN,
    DisplayableCuisine.DESSERT,
  ]),
  "chicken wings": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  "fast food": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  "hot dogs": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  buffets: Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  diners: Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  "hot pot": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  southern: Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  "tex-mex": Set<DisplayableCuisine>([DisplayableCuisine.AMERICAN]),
  "pub food": Set<DisplayableCuisine>([
    DisplayableCuisine.AMERICAN,
    DisplayableCuisine.BAR,
  ]),
  "beer, wine & spirits": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  breweries: Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  brewpubs: Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  cideries: Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  distilleries: Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "airport lounges": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "beer bar": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "champagne bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "cigar bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "cocktail bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "dive bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "drive-thru bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "gay bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "hookah bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "irish pub": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  lounges: Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  pubs: Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  speakeasies: Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "sports bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "tiki bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "vermouth bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "whiskey bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "wine bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "beer gardens": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "tapas bars": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  "tapas/small plates": Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
  bagels: Set<DisplayableCuisine>([DisplayableCuisine.CAFE]),
  "coffee & tea": Set<DisplayableCuisine>([DisplayableCuisine.CAFE]),
  "coffee roasteries": Set<DisplayableCuisine>([DisplayableCuisine.CAFE]),
  "bubble tea": Set<DisplayableCuisine>([DisplayableCuisine.CAFE]),
  "internet cafes": Set<DisplayableCuisine>([DisplayableCuisine.CAFE]),
  "juice bars & smoothies": Set<DisplayableCuisine>([DisplayableCuisine.CAFE]),
  "tea rooms": Set<DisplayableCuisine>([DisplayableCuisine.CAFE]),
  "hawker centre": Set<DisplayableCuisine>([
    DisplayableCuisine.CHINESE,
    DisplayableCuisine.THAI,
  ]),
  chinese: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  cantonese: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  congee: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  "dim sum": Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  fuzhou: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  hainan: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  hakka: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  henghwa: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  hokkien: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  hunan: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  pekinese: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  shanghainese: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  szechuan: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  teochew: Set<DisplayableCuisine>([DisplayableCuisine.CHINESE]),
  "acai bowls": Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  bakeries: Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  "chimney cakes": Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  churros: Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  cupcakes: Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  "custom cakes": Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  desserts: Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  gelato: Set<DisplayableCuisine>([
    DisplayableCuisine.DESSERT,
    DisplayableCuisine.ITALIAN,
  ]),
  donuts: Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  "ice cream & frozen yogurt": Set<DisplayableCuisine>([
    DisplayableCuisine.DESSERT,
  ]),
  "milkshake bars": Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  "shaved ice": Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  "shaved snow": Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  "candy stores": Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  "chocolatiers & shops": Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  macarons: Set<DisplayableCuisine>([
    DisplayableCuisine.DESSERT,
    DisplayableCuisine.FRENCH,
  ]),
  "sugar shacks": Set<DisplayableCuisine>([DisplayableCuisine.DESSERT]),
  creperies: Set<DisplayableCuisine>([
    DisplayableCuisine.DESSERT,
    DisplayableCuisine.FRENCH,
  ]),
  andalusian: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  belgian: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  french: Set<DisplayableCuisine>([
    DisplayableCuisine.FRENCH,
    DisplayableCuisine.FRENCH,
  ]),
  alsatian: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  auvergnat: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  berrichon: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  bourguignon: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  mauritian: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  nicoise: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  provencal: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  reunion: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  "french southwest": Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  galician: Set<DisplayableCuisine>([DisplayableCuisine.FRENCH]),
  "hamburgers/burgers": Set<DisplayableCuisine>([DisplayableCuisine.HAMBURGER]),
  fries: Set<DisplayableCuisine>([DisplayableCuisine.HAMBURGER]),
  shakes: Set<DisplayableCuisine>([DisplayableCuisine.HAMBURGER]),
  "chicken sandwhich": Set<DisplayableCuisine>([DisplayableCuisine.HAMBURGER]),
  torshi: Set<DisplayableCuisine>([DisplayableCuisine.INDIAN]),
  indian: Set<DisplayableCuisine>([DisplayableCuisine.INDIAN]),
  panzerotti: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  piadina: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  "cheese shops": Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  zapiekanka: Set<DisplayableCuisine>([
    DisplayableCuisine.ITALIAN,
    DisplayableCuisine.PIZZA,
  ]),
  italian: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  abruzzese: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  altoatesine: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  apulian: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  calabrian: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  "cucina campana": Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  emilian: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  friulan: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  ligurian: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  lumbard: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  napoletana: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  piemonte: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  roman: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  sardinian: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  sicilian: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  tuscan: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  venetian: Set<DisplayableCuisine>([DisplayableCuisine.ITALIAN]),
  bento: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  "japanese sweets": Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  taiyaki: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  dagashi: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  japanese: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  blowfish: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  "conveyor belt sushi": Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  donburi: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  gyudon: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  oyakodon: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  "hand rolls": Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  horumon: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  izakaya: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  "japanese curry": Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  kaiseki: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  kushikatsu: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  oden: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  okinawan: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  okonomiyaki: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  onigiri: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  ramen: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  robatayaki: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  soba: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  sukiyaki: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  takoyaki: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  tempura: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  teppanyaki: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  tonkatsu: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  udon: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  unagi: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  "western style japanese food": Set<DisplayableCuisine>([
    DisplayableCuisine.JAPANESE,
  ]),
  yakiniku: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  yakitori: Set<DisplayableCuisine>([DisplayableCuisine.JAPANESE]),
  empanadas: Set<DisplayableCuisine>([DisplayableCuisine.MEXICAN]),
  tacos: Set<DisplayableCuisine>([
    DisplayableCuisine.MEXICAN,
    DisplayableCuisine.MEXICAN,
  ]),
  tortillas: Set<DisplayableCuisine>([DisplayableCuisine.MEXICAN]),
  mexican: Set<DisplayableCuisine>([DisplayableCuisine.MEXICAN]),
  "eastern mexican": Set<DisplayableCuisine>([DisplayableCuisine.MEXICAN]),
  jaliscan: Set<DisplayableCuisine>([DisplayableCuisine.MEXICAN]),
  "northern mexican": Set<DisplayableCuisine>([DisplayableCuisine.MEXICAN]),
  oaxacan: Set<DisplayableCuisine>([DisplayableCuisine.MEXICAN]),
  pueblan: Set<DisplayableCuisine>([DisplayableCuisine.MEXICAN]),
  tamales: Set<DisplayableCuisine>([DisplayableCuisine.MEXICAN]),
  yucatan: Set<DisplayableCuisine>([DisplayableCuisine.MEXICAN]),
  pizza: Set<DisplayableCuisine>([DisplayableCuisine.PIZZA]),
  "arab pizza": Set<DisplayableCuisine>([DisplayableCuisine.PIZZA]),
  fishmonger: Set<DisplayableCuisine>([DisplayableCuisine.SEAFOOD]),
  poke: Set<DisplayableCuisine>([DisplayableCuisine.SEAFOOD]),
  "fish & chips": Set<DisplayableCuisine>([DisplayableCuisine.SEAFOOD]),
  seafood: Set<DisplayableCuisine>([DisplayableCuisine.SEAFOOD]),
  "sushi bars": Set<DisplayableCuisine>([DisplayableCuisine.SEAFOOD]),
  steak: Set<DisplayableCuisine>([DisplayableCuisine.STEAK]),
  brazilian: Set<DisplayableCuisine>([DisplayableCuisine.STEAK]),
  "brazilian empanadas": Set<DisplayableCuisine>([
    DisplayableCuisine.STEAK,
    DisplayableCuisine.STEAK,
  ]),
  "central brazilian": Set<DisplayableCuisine>([
    DisplayableCuisine.STEAK,
    DisplayableCuisine.STEAK,
  ]),
  "northeastern brazilian": Set<DisplayableCuisine>([
    DisplayableCuisine.STEAK,
    DisplayableCuisine.STEAK,
  ]),
  "northern brazilian": Set<DisplayableCuisine>([
    DisplayableCuisine.STEAK,
    DisplayableCuisine.STEAK,
  ]),
  rodizios: Set<DisplayableCuisine>([
    DisplayableCuisine.STEAK,
    DisplayableCuisine.STEAK,
  ]),
  "nasi lemak": Set<DisplayableCuisine>([DisplayableCuisine.THAI]),
  thai: Set<DisplayableCuisine>([DisplayableCuisine.THAI]),
  cafe: Set<DisplayableCuisine>([DisplayableCuisine.CAFE]),
  bar: Set<DisplayableCuisine>([DisplayableCuisine.BAR]),
});
