//
//  LocalizedStrings.swift
//  Foncii
//
//  Created by Justin Cook on 2/10/23.
//

import Foundation
import SwiftUI

/// Note: If a new string is added to the localization file(s) please update these enums accordingly
enum LocalizedStrings: String, CaseIterable {
    // MARK: --- Shared
    // MARK: - App Specific:
    case APP_NAME,
         APP_SLOGAN,
         // MARK: - Shared Scenes:
         ONE_TIME_PASSCODE,
         LOG_IN,
         SIGN_UP,
         USERNAME,
         PASSWORD,
         EMAIL,
         PHONE_NUMBER,
         FULL_NAME,
         OR,
         SEND,
         REQUEST,
         EMAIL_PLACEHOLDER,
         CONFIRMATION_MESSAGE_1,
         DONE,
         SUBMIT,
         NEXT,
         SKIP,
         SEARCH,
         RESTAURANT_SEARCHBAR_PLACEHOLDER,
         TEXT_FIELD_PLACEHOLDER_SEARCH_BY_NAME,
         LOCATION_UNAVAILABLE,
         HI_GREETING,
         NO_SEARCH_RESULTS,
         FAILED_FETCH_REQUEST,
         UPDATE,
         MAJOR_CITIES,
         COMPLETE,
         VIEW_ALL,
         SETTINGS,
         NOTIFICATIONS,
         BREAKFAST,
         LUNCH,
         DINNER,
         DESSERT,
         ONE_DOLLAR_SIGN,
         TWO_DOLLAR_SIGNS,
         THREE_DOLLAR_SIGNS,
         FOUR_DOLLAR_SIGNS,
         LOG_OUT,
         MATCH,
         
         // MARK: --- Other
         // MARK: - Networking Service Diagnostic Information
         HUMAN_READABLE_INTERNET_UNAVAILABLE_UNKNOWN_REASON,
         HUMAN_READABLE_INTERNET_NOT_AVAILABLE,
         HUMAN_READABLE_INTERNET_CELLULAR_DENIED,
         HUMAN_READABLE_INTERNET_WIFI_DENIED,
         HUMAN_READABLE_INTERNET_LOCAL_NETWORK_DENIED,
         
         // MARK: --- Specific Scenes
         // MARK: -- Main Scene
         // MARK: - Home Tab
         // MARK: - Home Screen:
         HOME_SCREEN_FYP_TAB_TITLE,
         HOME_SCREEN_TRENDING_TAB_TITLE,
         
         // MARK: - Date and Location Editor:
         DATE_AND_LOCATION_EDITOR_INPUT_1_TITLE,
         DATE_AND_LOCATION_EDITOR_INPUT_2_TITLE,
         DATE_AND_LOCATION_EDITOR_INPUT_2_TEXT,
         
         // MARK: - Map Tab
         // MARK: - Map Screen:
         
         // MARK: - Profile Tab
         // MARK: - Profile Screen:
         PROFILE_SCREEN_FAVORITES_TAB_TITLE,
         PROFILE_SCREEN_RECOMMENDATIONS_TAB_TITLE,
         PROFILE_SCREEN_LOCATIONS_HEADER_TEXT,
         PROFILE_SCREEN_NO_RECOMMENDATIONS_FOUND_PROMPT,
         PROFILE_SCREEN_NO_FAVORITES_FOUND_PROMPT,
         
         // MARK: - Settings Screen
         SETTINGS_SCREEN_PROFILE_INFORMATION_ROW_TITLE,
         SETTINGS_SCREEN_PROFILE_INFORMATION_ROW_SUBTITLE,
         SETTINGS_SCREEN_UPDATE_TASTE_PROFILE_ROW_TITLE,
         SETTINGS_SCREEN_UPDATE_TASTE_PROFILE_ROW_SUBTITLE,
         SETTINGS_SCREEN_CHANGE_PASSWORD_ROW_TITLE,
         SETTINGS_SCREEN_CHANGE_PASSWORD_ROW_SUBTITLE,
         SETTINGS_SCREEN_REFER_TO_FRIENDS_ROW_TITLE,
         SETTINGS_SCREEN_REFER_TO_FRIENDS_ROW_SUBTITLE,
         SETTINGS_SCREEN_PUSH_NOTIFICATIONS_ROW_TITLE,
         SETTINGS_SCREEN_PUSH_NOTIFICATIONS_ROW_SUBTITLE,
         SETTINGS_SCREEN_RATE_US_ROW_TITLE,
         SETTINGS_SCREEN_RATE_US_ROW_SUBTITLE,
         SETTINGS_SCREEN_HELP_AND_SUPPORT_ROW_TITLE,
         SETTINGS_SCREEN_HELP_AND_SUPPORT_ROW_SUBTITLE,
         
         // MARK: - Taste Profile Questionnaire Screen
         // Page Title
         TASTE_PROFILE_ADVENTURE_LEVEL_QUESTION_PAGE_HEADER,
         TASTE_PROFILE_DRINK_PREFERENCE_QUESTION_PAGE_HEADER,
         TASTE_PROFILE_RESTAURANT_RATING_IMPORTANCE_LEVEL_QUESTION_PAGE_HEADER,
         TASTE_PROFILE_FOOD_ATMOSPHERE_SERVICE_BALANCE_QUESTION_PAGE_HEADER,
         TASTE_PROFILE_PREFERRED_MEAL_TYPES_QUESTION_PAGE_HEADER,
         TASTE_PROFILE_PREFERRED_PRICE_LEVELS_QUESTION_PAGE_HEADER,
         TASTE_PROFILE_DISTANCE_PREFERENCE_LEVEL_QUESTION_PAGE_HEADER,
         TASTE_PROFILE_CUISINE_PREFERENCE_QUESTION_PAGE_HEADER,
         TASTE_PROFILE_FOOD_RESTRICTION_PREFERENCE_QUESTION_PAGE_HEADER,
         
         // Suggestion Entry
         TASTE_PROFILE_SUGGESTION_ENTRY_PLACEHOLDER,
         TASTE_PROFILE_SUGGESTION_ENTRY_PROMPT,
         
         // MARK: - Taste Profile Q&As
         // Question
         TASTE_PROFILE_ADVENTURE_LEVEL_QUESTION_TITLE,
         // Answers
         TASTE_PROFILE_ADVENTURE_LEVEL_QUESTION_ANSWER_1,
         TASTE_PROFILE_ADVENTURE_LEVEL_QUESTION_ANSWER_2,
         TASTE_PROFILE_ADVENTURE_LEVEL_QUESTION_ANSWER_3,
         TASTE_PROFILE_ADVENTURE_LEVEL_QUESTION_ANSWER_4,
         
         // Question
         TASTE_PROFILE_DRINK_PREFERENCE_QUESTION_TITLE,
         // Answers
         TASTE_PROFILE_DRINK_PREFERENCE_QUESTION_ANSWER_1,
         TASTE_PROFILE_DRINK_PREFERENCE_QUESTION_ANSWER_2,
         
         // Question
         TASTE_PROFILE_RESTAURANT_RATING_IMPORTANCE_LEVEL_QUESTION_TITLE,
         // Answers
         TASTE_PROFILE_RESTAURANT_RATING_IMPORTANCE_LEVEL_QUESTION_ANSWER_1,
         TASTE_PROFILE_RESTAURANT_RATING_IMPORTANCE_LEVEL_QUESTION_ANSWER_2,
         TASTE_PROFILE_RESTAURANT_RATING_IMPORTANCE_LEVEL_QUESTION_ANSWER_3,
         TASTE_PROFILE_RESTAURANT_RATING_IMPORTANCE_LEVEL_QUESTION_ANSWER_4,
         
         // Question
         TASTE_PROFILE_FOOD_ATMOSPHERE_SERVICE_BALANCE_QUESTION_TITLE,
         TASTE_PROFILE_FOOD_ATMOSPHERE_SERVICE_BALANCE_QUESTION_ANSWER_1,
         TASTE_PROFILE_FOOD_ATMOSPHERE_SERVICE_BALANCE_QUESTION_ANSWER_2,
         TASTE_PROFILE_FOOD_ATMOSPHERE_SERVICE_BALANCE_QUESTION_ANSWER_3,
         TASTE_PROFILE_FOOD_ATMOSPHERE_SERVICE_BALANCE_QUESTION_ANSWER_4,
         
         // Question
         TASTE_PROFILE_PREFERRED_MEAL_TYPES_QUESTION_TITLE,
         
         // Question
         TASTE_PROFILE_PREFERRED_PRICE_LEVELS_QUESTION_TITLE,
         
         // Question
         TASTE_PROFILE_DISTANCE_PREFERENCE_LEVEL_QUESTION_TITLE,
         // Answers
         TASTE_PROFILE_DISTANCE_PREFERENCE_LEVEL_QUESTION_ANSWER_1,
         TASTE_PROFILE_DISTANCE_PREFERENCE_LEVEL_QUESTION_ANSWER_2,
         TASTE_PROFILE_DISTANCE_PREFERENCE_LEVEL_QUESTION_ANSWER_3,
         TASTE_PROFILE_DISTANCE_PREFERENCE_LEVEL_QUESTION_ANSWER_4,
         
         // Question
         TASTE_PROFILE_CUISINE_PREFERENCE_QUESTION_TITLE,
         
         // Question
         TASTE_PROFILE_FOOD_RESTRICTION_PREFERENCE_QUESTION_TITLE,
         
         // MARK: -- Onboarding Scene
         // MARK: - Login Screen:
         LOGIN_SCREEN_PROMPT_SUBTITLE_FRAGMENT_1,
         LOGIN_SCREEN_PROMPT_SUBTITLE_FRAGMENT_2,
         LOGIN_SCREEN_PROMPT_CREATE_NEW_ACCOUNT_BUTTON_TEXT,
         LOGIN_SCREEN_INPUT_FIELD_1_PLACEHOLDER,
         LOGIN_SCREEN_INCORRECT_USER_IDENTIFIER,
         LOGIN_SCREEN_INCORRECT_PASSWORD,
         LOGIN_SCREEN_FORGOT_LOGIN_PROMPT_FRAGMENT_1,
         LOGIN_SCREEN_FORGOT_LOGIN_PROMPT_FRAGMENT_2,
         LOGIN_SCREEN_FORGOT_LOGIN_PROMPT_FRAGMENT_3,
         
         // MARK: - Reset Password Screen:
         RESET_PASSWORD_SCREEN_TITLE_LOGGED_OUT,
         RESET_PASSWORD_SCREEN_TITLE_LOGGED_IN,
         RESET_PASSWORD_SCREEN_INSTRUCTIONS,
         RESET_PASSWORD_SCREEN_UNKNOWN_EMAIL,
         
         // MARK: - Forgot Username Screen:
         FORGOT_USERNAME_SCREEN_TITLE,
         FORGOT_USERNAME_SCREEN_INSTRUCTIONS,
         FORGOT_USERNAME_SCREEN_UNKNOWN_EMAIL,
         
         // MARK: - Sign Up Screen:
         SIGN_UP_SCREEN_PROMPT_SUBTITLE_FRAGMENT_1,
         SIGN_UP_SCREEN_PROMPT_SUBTITLE_FRAGMENT_2,
         SIGN_UP_SCREEN_PROMPT_SUBTITLE_FRAGMENT_3,
         SIGN_UP_SCREEN_PHONE_NUMBER_INSTRUCTIONS,
         SIGN_UP_SCREEN_USERNAME_INSTRUCTIONS,
         SIGN_UP_SCREEN_PASSWORD_INSTRUCTIONS,
         SIGN_UP_SCREEN_PHONE_NUMBER_ALREADY_IN_USE_WARNING,
         SIGN_UP_SCREEN_EMAIL_ALREADY_IN_USE_WARNING,
         SIGN_UP_SCREEN_USERNAME_ALREADY_IN_USE_WARNING,
         
         // MARK: - OTP Screen
         OTP_SCREEN_SUBHEADING,
         OTP_SCREEN_TOP_PROMPT,
         OTP_SCREEN_RESEND_PROMPT_FRAGMENT_1,
         OTP_SCREEN_RESEND_PROMPT_FRAGMENT_2,
         
         // MARK: - Enable Location Screen
         ENABLE_LOCATION_SCREEN_TITLE_FRAGMENT_1,
         ENABLE_LOCATION_SCREEN_TITLE_FRAGMENT_2,
         ENABLE_LOCATION_SCREEN_TITLE_FRAGMENT_3,
         ENABLE_LOCATION_SCREEN_TITLE_FRAGMENT_4,
         ENABLE_LOCATION_SCREEN_TITLE_FRAGMENT_5,
         ENABLE_LOCATION_SCREEN_TITLE_FRAGMENT_6,
         ENABLE_LOCATION_SCREEN_SUBTITLE,
         ENABLE_LOCATION_SCREEN_BUTTON_TITLE,
         
         // MARK: - Aggregation Phase Overlay
         AGGREGATION_PHASE_OVERLAY_SEARCHING_STATE_TITLE,
         AGGREGATION_PHASE_OVERLAY_INDEXING_STATE_TITLE,
         AGGREGATION_PHASE_OVERLAY_DONE_STATE_TITLE,
         AGGREGATION_PHASE_OVERLAY_FAILED_STATE_TITLE,
         AGGREGATION_PHASE_OVERLAY_SUBTITLE,
         
         // MARK: - Select Favorite Restaurants Screen
         SELECT_FAVORITES_SCREEN_TITLE,
         
         // MARK: - Alert Titles, Messages, and Action Descriptions
         // Generic Alert Strings
         GENERIC_ALERT_TITLE,
         GENERIC_ALERT_MESSAGE,
         GENERIC_ALERT_OK_ACTION,
         GENERIC_ALERT_CANCEL_ACTION,
         GENERIC_ALERT_RETRY_ACTION,
         GENERIC_ALERT_CONFIRM_ACTION,
         GENERIC_ALERT_SUBMIT_ACTION,
         GENERIC_ALERT_DELETE_ACTION,
         
         // MARK: - Error Alerts
         // OTP Errors
         OTP_ERROR_ALERT_TITLE,
         OTP_ERROR_VALIDATION_UNAVAILABLE_ALERT_MESSAGE,
         OTP_ERROR_REQUEST_UNAVAILABLE_ALERT_MESSAGE,
         OTP_ERROR_RESEND_REQUEST_UNAVAILABLE_ALERT_MESSAGE,
         OTP_ERROR_VALIDATION_FAILED_ALERT_MESSAGE,
         
         // Forgot Password Errors
         FORGOT_PASSWORD_ERROR_TITLE,
         FORGOT_PASSWORD_ERROR_REQUEST_LIMIT_REACHED_ALERT_MESSAGE,
         FORGOT_PASSWORD_ERROR_REQUEST_FAILED_ALERT_MESSAGE,
         
         // Forgot Username Errors
         FORGOT_USERNAME_ERROR_TITLE,
         FORGOT_USERNAME_ERROR_REQUEST_LIMIT_REACHED_ALERT_MESSAGE,
         FORGOT_USERNAME_ERROR_REQUEST_FAILED_ALERT_MESSAGE,
         
         // Login Errors
         LOGIN_ERROR_ALERT_TITLE,
         LOGIN_ERROR_NO_USER_DATA_FETCHED_ALERT_MESSAGE,
         
         // Sign Up Errors
         SIGN_UP_ERROR_ALERT_TITLE,
         SIGN_UP_ERROR_NO_USER_DATA_FETCHED_ALERT_MESSAGE,
         SIGN_UP_ERROR_FIREBASE_USER_CREATION_FAILED_MESSAGE,
         
         // Aggregation Errors
         AGGREGATION_ERROR_ALERT_TITLE,
         AGGREGATION_ERROR_NO_INTERNET_ALERT_MESSAGE,
         
         // Restaurant Interaction Errors
         RESTAURANT_INTERACTION_ERROR_ALERT_TITLE,
         RESTAURANT_INTERACTION_ERROR_OPERATION_FAILED_ALERT_MESSAGE,
         
         // Network Errors
         NETWORK_ERROR_ALERT_TITLE,
         NETWORK_ERROR_INTERNET_UNAVAILABLE_ALERT_MESSAGE
    
         // MARK: - Confirmation Alerts
         // ...
}

extension LocalizedStrings {
    /// String keys for SwiftUI and compiler time localization
    static func getLocalizedStringKey(for key: LocalizedStrings) -> LocalizedStringKey {
        return LocalizedStringKey(key.rawValue)
    }
    
    /// Strings for UIKit and manual localization
    static func getLocalizedString(for string: LocalizedStrings) -> String {
        return string.rawValue.localized
    }
}

