// Dependencies
// Types
import { FonciiEvents } from "../../types/common";

// Inheritance
import FonciiEventModel from "./protocol/fonciiEventModel";

export default class TasteProfileCreationEventModel
  extends FonciiEventModel
  implements TasteProfileCreationEvent, Objectable<TasteProfileCreationEvent>
{
  // Properties
  tasteProfileData: TasteProfile;
  autoGenerated: boolean;
  isDefault: boolean;

  constructor({
    id,
    userID,
    timestamp,
    tasteProfileData,
    autoGenerated,
    isDefault,
    sessionID,
  }: Partial<TasteProfileCreationEvent> & {
    tasteProfileData: TasteProfile;
    autoGenerated: boolean;
    isDefault: boolean;
  }) {
    super({
      id,
      userID,
      timestamp,
      eventType: FonciiEvents.TASTE_PROFILE_CREATION,
      sessionID,
    });

    this.tasteProfileData = tasteProfileData;
    this.autoGenerated = autoGenerated;
    this.isDefault = isDefault;
  }

  /**
   * @returns An object converted from JSON format representing the event model's data
   * or the data of any class that extends this class via inheritance.
   */
  toObject<TasteProfileCreationEvent>(): TasteProfileCreationEvent {
    return JSON.parse(JSON.stringify(this));
  }
}
