// Generated Cuisine Data Code
// * DO NOT EDIT *
/**
 * A collection of known aliases for different cuisines for us to map
 * similar restaurant specific categories from different data sources to our supported cuisines
 */
export const CuisineAliases = {
  afghan: ["Afghan", "Kabuli Pulao", "Mantu", "Afghan kebabs"],
  algerian: ["Algerian", "Couscous", "Chakhchoukha", "Mechoui"],
  american: [
    "American",
    "Classic American diner",
    "Apple pie",
    "BBQ ribs",
    "Bagels",
    "Classic burgers",
    "Gourmet burgers",
    "Veggie burgers",
    "Burgers",
    "Southern Cuisine",
    "Tex-Mex",
    "California Cuisine",
    "Soul Food",
    "Hamburgers",
    "Hot Dogs",
    "Fried Chicken",
    "Barbecue Ribs",
    "Macaroni and Cheese",
    "Apple Pie",
    "Buffalo Wings",
    "Cheeseburgers",
    "Pancakes",
    "Doughnuts",
    "Clam Chowder Philly Cheesesteak",
    "Fried Catfish",
    "Gumbo",
    "Cornbread",
    "BBQ Pulled Pork",
    "Cobb Salad",
    "Reuben Sandwich",
    "Key Lime Pie",
    "Chili",
    "Shrimp and Grits",
    "Cinnamon Rolls",
    "Steak Pot Roast",
    "Mashed Potatoes",
    "Corn on the Cob",
    "Tater Tots",
    "Fried Green Tomatoes",
  ],
  argentinian: [
    "Argentinian",
    "Empanadas",
    "Asado",
    "Chimichurri",
    "Milanesa",
    "Provoleta",
    "Humita en Chala",
    "Locro",
    "Matambre a la Pizza",
    "Fugazza",
    "Picada",
    "Choripán",
    "Provoleta",
    "Empanada Tucumana",
    "Parrilla Mixta",
    "Humita en Choclo",
    "Bife de Chorizo",
    "Dulce de Leche Desserts",
    "Alfajores",
    "Argentine Wine and Malbec",
    "Medialunas",
    "Lomito Sandwich",
    "Sorrentinos",
    "Panqueques con Dulce de Leche",
    "Pastel de Papa",
    "Tortas",
    "Matambre a la leche",
    "Yerba Mate Drink",
    "Cazuela de Mariscos",
    "Helado",
  ],
  armenian: ["Armenian", "Dolma", "Khorovats", "Lavash"],
  australian: ["Australian", "Kangaroo steak", "Lamingtons", "Meat pies"],
  austrian: ["Austrian", "Wiener Schnitzel", "Apfelstrudel", "Sacher Torte"],
  bbq: [
    "BBQ",
    "Brisket",
    "Pulled Pork",
    "Ribs",
    "Chicken Wings",
    "Sausages",
    "Burnt Ends",
    "Tri-Tip",
    "Pork Belly",
    "BBQ Chicken",
    "Beef Ribs",
    "Cornbread",
    "Macaroni and Cheese",
    "Baked Beans",
    "Coleslaw",
    "Potato Salad",
    "Collard Greens",
    "BBQ Sauce Varieties",
    "Grilled Corn on the Cob",
    "Peach Cobbler",
    "BBQ Nachos",
    "BBQ Tacos",
    "BBQ Pizza",
    "BBQ Sandwiches",
    "BBQ Salad",
    "BBQ Shrimp",
    "BBQ Burger",
    "BBQ Turkey",
    "BBQ Pork Sliders",
    "BBQ Tofu",
    "BBQ Beef Sandwich",
  ],
  bakery_cafe: [
    "Bakery/Cafe",
    "Fresh pastries",
    "Artisan bread",
    "Scones",
    "Sourdough",
    "Espresso",
    "Latte",
    "Cold brew",
    "Coffee",
    "Croissants",
    "Baguettes",
    "Pastries",
    "Espresso",
    "Cappuccino",
    "Macarons",
    "Scones",
    "Quiches",
    "Muffins",
    "Tarts",
    "Bread Pudding",
    "Coffee Cake",
    "Danish Pastry",
    "Eclairs",
    "Flat Whites",
    "Latte",
    "Americano",
    "Biscotti",
    "Tea Varieties",
    "Croissant Sandwiches",
    "Fruit Tarts",
    "Cheesecake",
    "Brownies",
    "Mille-Feuille",
    "Almond Croissants",
    "Pies",
    "Shortbread",
    "Chocolate Babka",
    "Cannoli",
    "Kouign-Amann",
  ],
  balkan: ["Balkan", "Cevapi", "Burek", "Ajvar"],
  bangladeshi: ["Bangladeshi", "Bharta", "Bhuna Khichuri", "Ilish Bhapa"],
  bar_wine_bar: [
    "Bar/Wine Bar",
    "Cocktail bar",
    "Craft beer bar",
    "Wine bar",
    "Pub snacks",
    "Appetizers",
    "Finger foods",
    "Charcuterie board",
    "Nachos",
    "Snacks",
    "Cheese",
    "Craft beer",
    "Beer pairing",
    "Brewery",
    "Spirits",
    "Cheese platter",
    "Cheese fondue",
    "Cheese varieties",
    "Wine tasting",
    "Wine and cheese pairingCocktails",
    "Craft Beers",
    "Wine Selection",
    "Whiskey and Scotch",
    "Happy Hour Specials",
    "Charcuterie Boards",
    "Tapas",
    "Signature Cocktails",
    "Local Brews",
    "Specialty Martinis",
    "Wine Flights",
    "Bar Snacks",
    "Gin and Tonic Varieties",
    "Aperitifs",
    "Boozy Milkshakes",
    "Draft Beers",
    "Prosecco and Champagne",
    "Small Plates",
    "Bourbon Selection",
    "Artisanal Spirits",
    "Mojitos",
    "Signature Shots",
    "Margaritas",
    "Sangria",
    "Barbecue Bites",
    "Classic Cocktails",
  ],
  bengali: ["Bengali", "Bengali sweets", "Fish curry", "Panta bhat"],
  bhutanese: ["Bhutanese", "Ema datshi", "Phaksha Paa"],
  brazilian: [
    "Brazilian",
    "Feijoada",
    "Coxinha",
    "Pão de Queijo",
    "Brigadeiros",
    "Churrasco",
    "Moqueca",
    "Acarajé",
    "Açaí Bowl",
    "Caipirinha",
    "Quindim",
    "Pastel",
    "Vatapá",
    "Farofa",
    "Brazilian BBQ",
    "Empada",
    "Cachaça Cocktails",
    "Escondidinho",
    "Guarana Soda",
    "Tapioca",
    "Cuscuz",
    "Beijinho",
    "Canjica",
    "Churrasco Skewers",
    "Picanha",
    "Rabanada",
    "Bolo de Rolo",
    "Cocada",
    "Caldo Verde",
    "Brazilian Coffee",
    "Guava Paste",
    "Brazilian Sausages",
  ],
  breakfast: [
    "Breakfast",
    "Pancakes",
    "Diner",
    "Cafe",
    "Bakery",
    "Omelets",
    "Glazed donuts",
    "Filled donuts",
    "Specialty donuts",
    "Donuts",
    "Avocado toast",
    "Brunch",
    "Eggs Benedict",
    "Mimosa",
    "Brunch cocktails",
    "Breakfast burrito",
    "Bottomless brunch",
    "Waffles",
    "French Toast",
    "Scrambled Eggs",
    "Eggs Benedict",
    "Breakfast Burritos",
    "Breakfast Sandwiches",
    "Bagels and Lox",
    "Granola Parfait",
    "Açaí Bowl",
    "Smoothies",
    "Greek Yogurt with Fruit",
    "Belgian Waffles",
    "Huevos Rancheros",
    "Chia Seed Pudding",
    "Bacon and Eggs",
    "Sausage Links",
    "Hash Browns",
    "Cinnamon Rolls",
    "Breakfast Potatoes",
    "Croissants",
    "Frittatas",
    "English Breakfast",
    "Muffins",
    "Breakfast Tacos",
    "Biscuits and Gravy",
    "Fruit Salad",
    "Coffee",
    "Tea Varieties",
  ],
  british: [
    "British",
    "Fish and chips",
    "Bangers and Mash",
    "Full English Breakfast",
    "Shepherd's Pie",
    "Beef Wellington",
    "Chicken Tikka Masala",
    "Cornish Pasty",
    "Ploughman's Lunch",
    "Black Pudding",
    "Roast Beef and Yorkshire Pudding",
    "Scotch Egg",
    "Sticky Toffee Pudding",
    "Eton Mess",
    "Pimm's",
    "Crumpets",
    "Scones with Clotted Cream",
    "Welsh Rarebit",
    "Steak and Kidney Pie",
    "Cumberland Sausage",
    "Toad in the Hole",
    "Trifle",
    "Bubble and Squeak",
    "Kedgeree",
    "Jellied Eels",
    "Chicken and Leek Pie",
    "Haggis (Scottish)",
    "Neeps and Tatties (Scottish)",
    "Eccles Cake",
  ],
  burmese: ["Burmese", "Mohinga", "Tea leaf salad"],
  cajun: [
    "Cajun",
    "Gumbo",
    "Jambalaya",
    "Étouffée",
    "Boudin",
    "Po' boy sandwich",
    "Red Beans and Rice",
    "Crawfish Boil",
    "Muffuletta",
    "Alligator",
    "Andouille Sausage",
    "Blackened Catfish",
    "Shrimp Creole",
    "Beignets",
    "Dirty Rice",
    "Cajun Fried Chicken",
    "Crawfish Étouffée",
    "King Cake",
    "Oyster Po' Boy",
    "Cajun Crab Boil",
    "Shrimp and Grits",
    "Redfish Courtbouillon",
    "Cajun Corn Maque Choux",
    "Turducken",
    "Cajun Meat Pies",
    "Cajun Boudin Balls",
    "Shrimp Po' Boy",
    "Bread Pudding with Whiskey Sauce",
    "Pralines",
  ],
  cambodian: ["Cambodian", "Amok", "Nom Banh Chok", "Bai Sach Chrouk"],
  canadian: ["Canadian", "Poutine", "Butter tarts", "Nanaimo bars"],
  caribbean: [
    "Caribbean",
    "Jamaica",
    "Jerk Chicken",
    "Rice and Peas",
    "Ackee and Saltfish",
    "Curry Goat",
    "Plantains",
    "Trinidad and Tobago",
    "Roti",
    "Doubles",
    "Callaloo",
    "Pelau",
    "Aloo Pie",
    "Barbados",
    "Flying Fish and Cou-Cou",
    "Pudding and Souse",
    "Bajan Macaroni Pie",
    "Conkies",
    "Haiti",
    "Griot (Fried Pork)",
    "Joumou Soup",
    "Marinad",
    "Haitian Patties",
    "Cuba",
    "Ropa Vieja",
    "Moros y Cristianos",
    "Tostones",
    "Yuca con Mojo",
    "Puerto Rico",
    "Mofongo",
    "Arroz con Gandules",
    "Pernil",
    "Pastelón",
    "Dominican Republic",
    "Mangu",
    "Sancocho",
    "Tostones",
    "Mofongo",
    "Bahamas",
    "Conch Salad",
    "Bahamian Rock Lobster",
    "Johnnycake",
    "Bahama Mama (Cocktail)",
    "Grenada",
    "Oil Down",
    "Nutmeg Ice Cream",
    "Roti",
    "Grenadian Chocolate",
    "Saint Lucia",
    "Green Fig and Saltfish",
    "Breadfruit Pie",
    "Bouyon",
    "Green Banana and Saltfish Salad",
  ],
  chinese: [
    "Chinese",
    "Dim Sum",
    "Peking Duck",
    "Mapo Tofu",
    "Shumai",
    "Har gow",
    "Bao",
    "Hot Pot",
    "Spring Rolls",
    "Kung Pao Chicken",
    "Sweet and Sour Pork",
    "Mapo Tofu",
    "Chow Mein",
    "Wonton Soup",
    "Dumplings",
    "General Tso's Chicken",
    "Fried Rice",
    "Szechuan Beef",
    "Lo Mein",
    "Xiao Long Bao",
    "Ma Po Eggplant",
    "Hainanese Chicken Rice",
    "Crab Rangoon",
    "Baozi",
    "Prawn Toast",
    "Moo Shu Pork",
    "Orange Chicken",
    "Dan Dan Noodles",
    "Mongolian Beef",
    "Congee",
    "Salt and Pepper Shrimp",
    "Scallion Pancakes",
    "Sesame Chicken",
    "Beef and Broccoli",
    "Lotus Leaf Rice",
    "Hong Kong-Style Milk Tea",
    "Szechuan",
  ],
  chino_latino: [
    "Chino Latino",
    "Chifa",
    "Chifa Fusion Dishes",
    "Lomo Saltado",
    "Arroz Chaufa",
    "Ceviche with Asian Influences",
    "Nikkei Cuisine",
    "Peruvian Sushi Rolls",
    "Peking Duck Tacos",
    "Chinese-Style Empanadas",
    "Latin-Inspired Dim Sum",
    "Tuna Tartare with Latin Flavors",
    "Chino Latino Noodle Bowls",
    "Stir-Fried Plantains",
    "Yucca Fries with Asian Dipping Sauce",
    "Teriyaki Tostones",
    "Asian-Latin Fusion Tamales",
    "Grilled Miso-Glazed Corn",
    "Asian-Inspired Causa",
    "Sesame Seared Arepas",
    "Kimchi Quesadillas",
    "Chaufa de Mariscos",
    "Spicy Tamarind Ribs",
    "Latin-Asian Fusion Tacos",
    "Wasabi Guacamole",
    "Ginger Mojitos",
    "Sake Sangria",
    "Yuzu Margaritas",
    "Asian-Latin Ceviche Tostadas",
    "Latin Sushi Burritos",
    "Chino Latino BBQ Skewers",
    "Picanha with Soy-Ginger Glaze",
    "Passion Fruit Mochi Ice Cream",
  ],
  colombian: [
    "Colombian",
    "Bandeja Paisa",
    "Ajiaco Soup",
    "Arepas",
    "Empanadas",
    "Tamales",
    "Lechona",
    "Sancocho",
    "Pandebono",
    "Almojábanas",
    "Bunuelos",
    "Changua",
    "Fritanga",
    "Patacones",
    "Chicharrón",
    "Obleas",
    "Guiso de Arequipe",
    "Sobrebarriga",
    "Hogao Sauce",
    "Mondongo",
    "Arroz con Coco",
    "Cazuela de Mariscos",
    "Posta Negra",
    "Avena Colombiana",
    "Chocoramo",
    "Manjar Blanco",
    "Champús",
    "Cuchuco de Trigo",
    "Lulada",
    "Calentado",
    "Cholado",
  ],
  creole: [
    "Creole",
    "Gumbo",
    "Jambalaya",
    "Étouffée",
    "Red Beans and Rice",
    "Crawfish Boil",
    "Beignets",
    "Po' Boy Sandwich",
    "Shrimp Creole",
    "Chicken and Sausage Gumbo",
    "Dirty Rice",
    "Muffuletta",
    "Bread Pudding",
    "Andouille Sausage",
    "Catfish Courtbouillon",
    "Shrimp and Okra Gumbo",
    "Blackened Fish",
    "Alligator Bites",
    "Creole Mustard Sauce",
    "Cajun Crab Cakes",
    "Seafood Grits",
    "Collard Greens",
    "Hushpuppies",
    "Sweet Potato Pie",
    "Pralines",
    "Creole Shrimp and Grits",
    "Oyster Po' Boy",
    "Turtle Soup",
    "Mirliton Casserole",
    "Corn and Crab Bisque",
    "Bananas Foster",
  ],
  cuban: [
    "Cuban",
    "Ropa Vieja",
    "Tostones",
    "Moros y Cristianos",
    "Picadillo",
    "Tamales",
    "Yuca con Mojo",
    "Lechón Asado",
    "Arroz con Pollo",
    "Media Noche Sandwich",
    "Tostones con Ceviche",
    "Cuban Black Beans",
    "Masitas de Puerco",
    "Cuban Sandwich",
    "Congri",
    "Yuca Frita",
    "Bistec de Palomilla",
    "Cuban Picadillo Empanadas",
    "Turrón",
    "Cuban Coffee",
    "Papas Rellenas",
    "Malanga Fritters",
    "Guava Pastries",
    "Mamey Smoothie",
    "Camarones Enchilados",
    "Cuban Pernil",
    "Churros",
    "Batidos",
    "Arroz Imperial",
    "Flan Cubano",
  ],
  czech: ["Czech", "Svickova", "Knedliky", "Trdelnik"],
  diner: [
    "Diner",
    "Pancakes",
    "Waffles",
    "Omelettes",
    "Hash Browns",
    "Bacon and Eggs",
    "French Toast",
    "Corned Beef Hash",
    "Club Sandwich",
    "Reuben Sandwich",
    "Chicken and Waffles",
    "Meatloaf",
    "Biscuits and Gravy",
    "BLT Sandwich",
    "Hot Dogs",
    "Milkshakes",
    "Patty Melt",
    "Tuna Melt",
    "Monte Cristo Sandwich",
    "Country Fried Steak",
    "Chicken Fried Chicken",
    "Grilled Cheese Sandwich",
    "Egg Salad Sandwich",
    "Turkey Club Sandwich",
    "Fried Chicken",
    "Mashed Potatoes",
    "Roast Beef Sandwich",
    "Chili",
    "Shakes and Malts",
    "Classic Breakfast Platter",
    "Fish and Chips",
  ],
  dominican: [
    "Dominican",
    "Mangu",
    "Mofongo",
    "Sancocho",
    "Mangú con Queso Frito",
    "Chicharrón de Pollo",
    "Tres Golpes Breakfast",
    "Pica Pollo",
    "Chivo Guisado",
    "Pernil",
    "Yaniqueques",
    "Pastelón de Plátano Maduro",
    "Mondongo",
    "Arepa Dominicana",
    "Habichuelas Guisadas",
    "Queso Frito",
    "Casabe",
    "Ensalada de Papa",
    "Bacalao Guisado",
    "Camarones Guisados",
    "Ceviche Dominicano",
    "Chimichurri Burger",
    "Locrio de Pollo",
    "Pastelitos Dominicanos",
    "Tostones",
    "Quipes",
    "Tuna Salad",
    "Habichuelas con Dulce",
    "Guandules con Coco",
    "Chinola",
    "Juice",
    "Morir Soñando",
  ],
  deli: [
    "Deli",
    "Deli sandwiches",
    "Reuben sandwich",
    "Matzo ball soup",
    "Bagel",
    "Pastrami Sandwich",
    "Corned Beef Sandwich",
    "Knish",
    "Bagels with Lox and Cream Cheese",
    "Deli Pickles",
    "Whitefish Salad",
    "Chopped Liver",
    "Turkey Club Sandwich",
    "Chicken Salad Sandwich",
    "Egg Salad Sandwich",
    "Nova Scotia Salmon Bagel",
    "Brisket Sandwich",
    "Turkey Reuben",
    "Hot Pastrami on Rye",
    "Black and White Cookie",
    "Deli Potato Salad",
    "Latkes",
    "Chicken Noodle Soup",
    "Kugel",
    "Pickled Herring",
    "Beef Tongue Sandwich",
    "Rueben Wrap",
    "Deli Coleslaw",
    "Lox and Bagel Sandwich",
    "Turkey and Swiss Sandwich",
    "Deli Mustard",
    "Deli Knoblewurst Sausage",
    "Deli Rye Bread",
    "Bacon egg, cheese",
    "Bogettega",
  ],
  dessert: [
    "Dessert",
    "Dessert bars",
    "Sweet treats",
    "Gelato",
    "Sorbet",
    "Ice cream sandwiches",
    "Popsicles",
    "Ice cream",
    "Cake",
    "Pie",
    "Brownies",
    "Tarts",
    "Mousse",
    "Banana Split",
    "Crème Brûlée",
    "Eclairs",
    "Baklava",
    "Macarons",
    "Bread Pudding",
    "Strawberry Shortcake",
    "Coconut Cream Pie",
    "Profiteroles",
    "Chocolate Fondue",
    "Peanut Butter Pie",
    "Tres Leches Cake",
    "Mochi Ice Cream",
    "Pecan Pie",
    "Rice Pudding",
    "Pineapple Upside-Down Cake",
  ],
  eastern_european: ["Eastern European", "Pierogi", "Borscht", "Cabbage rolls"],
  ecuadorian: ["Ecuadorian", "Ceviche", "Llapingachos"],
  egyptian: [
    "Egyptian",
    "Ful medames",
    "Koshari",
    "Falafel",
    "Shawarma",
    "Baba Ganoush",
    "Hummus",
    "Fattoush",
    "Molokhia",
    "Samak Mashwi",
    "Taameya",
    "Roz Bel Laban",
    "Basbousa",
    "Umm Ali",
    "Hawawshi",
    "Bamia",
    "Mulukhiyah",
    "Mahshi",
    "Warak Enab",
    "Egyptian Lentil Soup",
    "Roz Bel Laban",
    "Hawawshi",
    "Bissara",
    "Shakshuka",
    "Konafa",
    "Roz Bel Laban",
    "Gebna Makleyah",
    "Meshaltet",
    "Baladi Bread",
    "Helba Tea",
    "Sahlab Drink",
  ],
  ethiopian: [
    "Ethiopian",
    "Doro Wat",
    "Injera",
    "Kitfo",
    "Tibs",
    "Shiro",
    "Misir Wat",
    "Sega Wat",
    "Atayefo",
    "Tej",
    "Sambusa",
    "Alicha",
    "Firfir",
    "Dulet",
    "Ayibe",
    "Genfo",
    "Kik Alicha",
    "Gored Gored",
    "Timatim Fitfit",
    "Awaze Tibs",
    "Dulet",
    "Yebeg Tibs",
    "Duba Wat",
    "Ambasha Bread",
    "Gomen",
    "Enkulal Firfir",
    "Atakilt Wat",
    "Ingudai Tibs",
    "Taita",
  ],
  european: [
    "European",
    "Continental cuisine",
    "Baguette",
    "Croissant",
    "Paella",
    "Bratwurst",
    "Pretzel",
    "Goulash",
    "Tiramisu",
    "Spanakopita",
    "Baklava",
    "Wiener Schnitzel",
    "Risotto",
    "Tapenade",
    "Ratatouille",
    "Pesto Pasta",
    "Fish and Chips",
    "Borscht",
    "Pierogi",
    "Haggis",
    "Cabbage Rolls",
    "Black Forest Cake",
    "Stroopwafels",
    "Bouillabaisse",
    "Frittata",
    "Porchetta",
    "Rösti",
    "Biscotti",
    "Sauerbraten",
    "Crème Fraîche",
    "Kanelbulle",
    "Gulab Jamun",
    "Irish Stew",
  ],
  fast_food: [
    "Fast Food",
    "Quick bites",
    "Drive-thru",
    "Burgers",
    "French Fries",
    "Chicken Nuggets",
    "Pizza Slices",
    "Hot Dogs",
    "Soft Serve Ice Cream",
    "Onion Rings",
    "Fried Chicken",
    "Tacos",
    "Nachos",
    "Burritos",
    "Fried Fish Sandwich",
    "Chicken Sandwich",
    "Milkshakes",
    "Soda Floats",
    "Egg McMuffin",
    "Hash Browns",
    "Chicken Fries",
    "Mozzarella Sticks",
    "Grilled Cheese Sandwich",
    "Chicken Tenders",
    "Double Cheeseburger",
    "Fish and Chips",
    "BLT Sandwich",
    "Cheese Fries",
    "Veggie Burger",
    "Chili Cheese Fries",
    "McFlurry",
    "Apple Pie",
    "Chicken Wings",
    "Sliders",
    "Frosty",
  ],
  filipino: [
    "Filipino",
    "Adobo",
    "Sinigang",
    "Lechon",
    "Chicken Adobo",
    "Halo-Halo",
    "Lumpia",
    "Pancit",
    "Kare-Kare",
    "Bistek Tagalog",
    "Tapsilog",
    "Longganisa",
    "Balut",
    "Bibingka",
    "Taho",
    "Laing",
    "Dinuguan",
    "Puto",
    "Crispy Pata",
    "Sinangag",
    "Bulalo",
    "Sisig",
    "Ukoy",
    "Pinakbet",
    "Ginataang Halo-Halo",
    "Kakanin",
    "Champorado",
    "Tinola",
    "Inihaw na Bangus",
    "Pansit Malabon",
    "Ube Halaya",
    "Kwek-Kwek",
    "Chicken Inasal",
  ],
  french: [
    "French",
    "Baguette",
    "Croissant",
    "Escargot",
    "Coq au Vin",
    "Ratatouille",
    "Quiche Lorraine",
    "Bouillabaisse",
    "Boeuf Bourguignon",
    "Duck Confit",
    "Foie Gras",
    "Crème Brûlée",
    "Eclairs",
    "Tarte Tatin",
    "Pain Perdu",
    "Gratin Dauphinois",
    "Cassoulet",
    "Niçoise Salad",
    "Beef Tartare",
    "Profiteroles",
    "Macarons",
    "Pissaladière",
    "Chateaubriand",
    "Salade Lyonnaise",
    "Raclette",
    "Croque-Monsieur",
    "Mille-Feuille",
    "Boudin Noir",
    "Sole Meunière",
    "Ratatouille",
    "Crêpes",
    "Madeleines",
  ],
  fried_chicken: [
    "Fried Chicken",
    "Southern-style fried chicken",
    "Korean fried chicken",
    "Spicy fried chicken",
    "Chicken tenders",
    "Chicken nuggets",
    "Fried chicken sandwhich",
    "Nashville Hot Chicken",
    "Chicken Wings",
    "Popcorn Chicken",
    "Honey Butter Fried Chicken",
    "Japanese Karaage Chicken",
    "Coconut Fried Chicken",
    "Cajun Fried Chicken",
    "Garlic Parmesan Fried Chicken",
    "Buffalo Chicken",
    "Mexican Fried Chicken",
    "Thai Fried Chicken",
    "Teriyaki Fried Chicken",
    "Lemon Pepper Fried Chicken",
    "Crispy Chicken Sandwich",
    "Chicken and Waffles",
    "Beer-Battered Fried Chicken",
    "Chinese Salt and Pepper Chicken",
    "Indian Fried Chicken",
    "BBQ Fried Chicken",
    "Panko-Crusted Fried Chicken",
    "Southern Style Chicken Biscuits",
    "Sriracha Fried Chicken",
    "Spicy Honey Fried Chicken",
    "Maple Glazed Fried Chicken",
    "Ranch Fried Chicken",
    "Peri-Peri Fried Chicken",
  ],
  georgian: ["Georgian", "Khachapuri", "Khinkali", "Satsivi"],
  german: [
    "German",
    "Bratwurst",
    "Sauerkraut",
    "Pretzels",
    "Schnitzel",
    "Weisswurst",
    "Currywurst",
    "Sauerbraten",
  ],
  greek: [
    "Greek",
    "Souvlaki",
    "Moussaka",
    "Gyro",
    "Spanakopita",
    "Tzatziki",
    "Fasolada",
    "Kalamata Olives",
    "Greek Salad",
    "Pastitsio",
    "Dolma",
    "Loukoumades",
    "Baklava",
    "Taramasalata",
    "Octopus Salad",
    "Saganaki",
    "Avgolemono Soup",
    "Yemista",
    "Keftedes",
    "Melitzanosalata",
    "Souvlaki Pita",
    "Grilled Halloumi",
    "Greek Coffee",
    "Horiatiki Salad",
    "Tiropita",
    "Revithosoupa",
    "Kleftiko",
    "Galaktoboureko",
    "Kourabiedes",
    "Kolokythokeftedes",
    "Kalamata Olive Bread",
    "Grilled Calamari",
  ],
  guyanese: ["Guyanese", "Pepperpot", "Roti", "Metemgee"],
  haitian: [
    "Haitian",
    "Griot",
    "Joumou Soup",
    "Legim",
    "Marinad",
    "Lambi",
    "Diri Djon Djon",
    "Joumou Salad",
    "Bannann Peze",
    "Pikliz",
    "Griot Tacos",
    "Tassot",
    "Bouillon",
    "Marinad Salad",
    "Mayi Moulen ak Sòs Pwa",
    "Lambi Creole",
    "Dirizan",
    "Kalalou",
    "Macaroni au Gratin",
    "Akra",
    "Soup Joumou Tacos",
    "Pickliz Hot Dog",
    "Fritay Platter",
    "Pain Patate",
    "Kremas",
    "Mayi Boukannen",
    "Bouillon Soup",
    "Griot Burger",
    "Soup Joumou with Fried Egg",
    "Mayi Moulen Porridge",
    "Joumou Juice",
    "Douce Macoss",
  ],
  hawaiian: [
    "Hawaiian",
    "Poke",
    "Loco Moco",
    "Haupia",
    "Kalua Pork",
    "Huli Huli Chicken",
    "Spam Musubi",
    "Lau Lau",
    "Pipikaula",
    "Ahi Poke",
    "Poi",
    "Shave Ice",
    "Mochiko Chicken",
    "Lūʻau",
    "Huli Huli Ribs",
    "Lomi Lomi Salmon",
    "Manapua",
    "Malasadas",
    "Haupia Pie",
    "Ahi Tuna Burger",
    "Ono Poke",
    "Huli Huli Salmon",
    "Coconut Shrimp",
    "Hawaiian Pizza",
    "Haupia Pancakes",
    "Pulehu Steak",
    "Haupia Cake",
    "Hawaiian Garlic Shrimp",
    "Spam and Eggs",
    "Acai Bowl",
    "Kalbi Ribs",
    "Pineapple Upside-Down Cake",
  ],
  honduran: ["Honduran", "Baleadas", "Sopa de Caracol", "Pastelitos"],
  hot_dogs: [
    "Hot Dogs",
    "Gourmet hot dogs",
    "Korean Hot Dog",
    "Chicago Style Hot Dog",
    "New York Style Hot Dog",
    "Coney Dog",
    "Chili Cheese Dog",
    "Sonoran Hot Dog",
    "Seattle Dog",
    "Detroit Coney Dog",
    "Corn Dog",
    "Bacon-Wrapped Hot Dog",
    "Texas Tommy",
    "Slaw Dog",
    "Philly Cheesesteak Dog",
    "Philly Cheesesteak Dog",
    "Vegan Hot Dog",
  ],
  hot_pot: [
    "Hot Pot",
    "Chinese hot pot",
    "Shabu-shabu",
    "Korean hot pot (Jeongol)",
  ],
  hungarian: ["Hungarian", "Goulash", "Chicken paprikash"],
  ice_cream: [
    "Ice Cream",
    "Gelato",
    "Sorbet",
    "Ice cream sandwiches",
    "Popsicles",
  ],
  indian: [
    "Indian",
    "Chicken Curry",
    "Biryani",
    "Butter Chicken",
    "Tikka Masala",
    "Saag Paneer",
    "Dal Tadka",
    "Rogan Josh",
    "Tandoori Chicken",
    "Chana Masala",
    "Palak Paneer",
    "Aloo Gobi",
    "Samosas",
    "Naan",
    "Masala Dosa",
    "Chicken Korma",
    "Vindaloo",
    "Pani Puri",
    "Chicken Biryani",
    "Aloo Paratha",
    "Hyderabadi Biryani",
    "Bhindi Masala",
    "Rasgulla",
    "Gulab Jamun",
    "Jalebi",
    "Chole Bhature",
    "Chicken Saag",
    "Malai Kofta",
    "Pav Bhaji",
    "Dahi Puri",
    "Kheer",
    "Chicken Tikka",
    "Karahi Chicken",
  ],
  indonesian: ["Indonesian", "Nasi Goreng", "Satay", "Rendang"],
  israeli: ["Israeli", "Hummus", "Shakshuka", "Falafel"],
  italian: [
    "Italian",
    "Risotto",
    "Bruschetta",
    "Tiramisu",
    "Pasta",
    "Spaghetti",
    "Fettuccine Alfredo",
    "Carbonara",
    "Pizza",
    "Pepperoni",
    "Supreme",
    "Pizza Margherita",
    "Spaghetti Bolognese",
    "Fettuccine Alfredo",
    "Lasagna",
    "Risotto",
    "Caprese Salad",
    "Bruschetta",
    "Tiramisu",
    "Cannoli",
    "Ravioli",
    "Penne alla Vodka",
    "Eggplant Parmesan",
    "Gnocchi",
    "Prosciutto and Melon",
    "Osso Buco",
    "Calzone",
    "Arancini",
    "Pesto Pasta",
    "Minestrone Soup",
    "Seafood Linguine",
    "Shrimp Scampi",
    "Antipasto Platter",
    "Cioppino",
    "Panzanella Salad",
    "Lemon Sorbet",
    "Affogato",
    "Polenta",
    "Porchetta",
    "Cacio e Pepe",
    "Amatriciana",
  ],
  jamaican: [
    "Jamaican",
    "Jerk Chicken",
    "Rice and Peas",
    "Curried Goat",
    "Ackee and Saltfish",
    "Jerk Pork",
    "Jamaican Patty",
    "Escovitch Fish",
    "Festival",
    "Callaloo",
    "Oxtail Stew",
    "Jerk Shrimp",
    "Bammy",
    "Pepper Pot Soup",
    "Solomon Gundy",
    "Sorrel Drink",
    "Gizzada",
    "Cornmeal Porridge",
    "Manish Water",
    "Bulla Cake",
    "Blue Drawers (Dukunu)",
    "Jonkanoo Soup",
    "Jamaican Run Down",
    "Pineapple Ginger Juice",
    "Coconut Drops",
    "Sweet Potato Pudding",
    "Rum Cake",
    "Breadfruit",
    "Peanut Porridge",
    "Easter Bun and Cheese",
    "Fish Tea Soup",
    "Jamaica Blue Mountain Coffee",
  ],
  japanese: [
    "Japanese",
    "Ramen",
    "Tempura",
    "Sushi",
    "Shoyu ramen",
    "Miso ramen",
    "Tonkotsu ramen",
    "Udon",
    "Yakitori",
    "Okonomiyaki",
    "Takoyaki",
    "Miso Soup",
    "Chawanmushi",
    "Yakiniku",
    "Shabu-Shabu",
    "Sukiyaki",
    "Kaiseki",
    "Soba",
    "Tamago Sushi",
    "Edamame",
    "Gyoza",
    "Sake",
    "Matcha",
    "Mochi",
    "Dorayaki",
    "Taiyaki",
    "Wagashi",
    "Donburi",
    "Katsudon",
    "Gyudon",
    "Oyakodon",
    "Teriyaki Chicken",
    "Teriyaki Salmon",
    "Teriyaki Beef",
    "Hand rolls",
    "California roll",
    "Nigiri",
  ],
  jewish: [
    "Jewish",
    "Matzo Ball Soup",
    "Bagels with Lox and Cream Cheese",
    "Latkes",
    "Challah Bread",
    "Rugelach",
    "Chicken Soup",
    "Gefilte Fish",
    "Pastrami Sandwich",
    "Knish",
    "Brisket",
    "Kugel",
    "Babka",
    "Blintzes",
    "Hamentashen",
    "Shakshuka",
    "Chopped Liver",
    "Chicken Schmaltz",
    "Matzo Brei",
    "Charoset",
    "Tzimmes",
    "Pickled Herring",
    "Chicken Liver Pâté",
    "Sufganiyot",
    "Noodle Kugel",
    "Kreplach",
    "Mandelbrot",
    "Farfel",
    "Knish",
    "Stuffed Cabbage (Holishkes)",
    "Cholent",
    "Matzo Farfel Casserole",
    "Jewish Apple Cake",
    "Lekach",
  ],
  jordanian: ["Jordanian", "Mansaf"],
  korean: [
    "Korean",
    "Kimchi",
    "Bibimbap",
    "Bulgogi",
    "Kimbap",
    "Japchae",
    "Tteokbokki",
    "Samgyeopsal",
    "Kimchi Jjigae",
    "Sundubu Jjigae",
    "Jajangmyeon",
    "Haemul Pajeon",
    "Galbi",
    "Bossam",
    "Yukhoe",
    "Odeng",
    "Mandu",
    "Kimchi Fried Rice",
    "Soondubu Jjigae",
    "Dak Galbi",
    "Kimchi Bokkeumbap (Kimchi Fried Rice)",
    "Hwe Dup Bap",
    "Gimbap",
    "Kimchi Jun (Kimchi Pancake)",
    "Dolsot Bibimbap (Stone Pot Bibimbap)",
    "Ojingeo Bokkeum (Spicy Stir-Fried Squid)",
    "Gyeran Mari (Rolled Omelette)",
    "Patbingsu (Shaved Ice Dessert)",
    "Kimchi Japchae",
    "Bulgogi Jeon (Bulgogi Pancake)",
    "Japchae Bap (Japchae Rice Bowl)",
    "Kimchi Tofu Stir-Fry",
  ],
  "laos_(lao)": ["Laos (Lao)", "Laap", "Tam Mak Hoong", "Khao Niew"],
  latin: [
    "Latin",
    "Ceviche",
    "Tacos",
    "Al Pastor",
    "Carnitas",
    "Barbacoa",
    "Fish Tacos",
    "Birria Tacos",
    "Arepas",
    "Pupusas",
    "Empanadas",
    "Ropa Vieja",
    "Ajiaco",
    "Lomo Saltado",
    "Tamales",
    "Chimichurri",
    "Picanha",
    "Feijoada",
    "Mole Poblano",
    "Peruvian Chicken",
    "Cachapa",
    "Pabellón Criollo",
    "Churrasco",
    "Cau Cau",
    "Pastel de Choclo",
    "Anticuchos",
    "Bandeja Paisa",
    "Sopa de Mondongo",
    "Cuy (Guinea Pig)",
    "Ceviche de Conchas Negras",
    "Tacu Tacu",
    "Alfajores",
    "Pollo a la Brasa",
    "Pastelón",
    "Moqueca",
    "Atole",
    "Plátano Maduro con Queso",
    "Llapingachos",
    "Arroz con Pollo",
  ],
  lebanese: [
    "Lebanese",
    "Shawarma",
    "Hummus",
    "Falafel",
    "Kebabs",
    "Shish Tawook",
    "Kofta Kebab",
    "Baba Ganoush",
    "Fattoush",
    "Tabouleh",
    "Labneh",
    "Manakish",
    "Kafta",
    "Warak Enab (Grape Leaves)",
    "Batata Harra",
    "Sfiha",
    "Fatayer",
    "Kibbeh",
    "Makloubeh",
    "Moutabal",
    "Toum (Garlic Sauce)",
    "Mujadara",
    "Lebanese Rice with Vermicelli",
    "Loubieh Bi Zeit (Green Beans with Olive Oil)",
    "Jibneh Arabieh (Lebanese Cheese)",
    "Shanklish",
    "Maamoul",
    "Znoud El Sit",
    "Meghli",
    "Lebanese Chicken and Rice",
    "Lebanese Spinach Pies",
    "Lebanese Lentil Soup",
    "Lebanese Meat Pie (Sfeeha)",
    "Lebanese Pickled Turnips",
    "Lebanese Fattoush Salad",
    "Lebanese Chicken Shawarma",
  ],
  malaysian: ["Malaysian", "Nasi Lemak", "Laksa", "Satay"],
  mediterranean: [
    "Mediterranean",
    "Greek salad",
    "Hummus",
    "Falafel",
    "Tzatziki",
    "Kebabs",
    "Chicken Souvlaki",
    "Lamb Kofta Kebab",
    "Tabouleh",
    "Baba Ganoush",
    "Fattoush",
    "Spanakopita",
    "Moussaka",
    "Dolma",
    "Baklava",
    "Shawarma",
    "Labneh",
    "Manakish",
    "Pita Bread",
    "Grilled Halloumi",
    "Ceviche",
    "Caprese Salad",
    "Ratatouille",
    "Paella",
    "Tapenade",
    "Calamari",
    "Greek Lemon Potatoes",
    "Stuffed Grape Leaves",
    "Olive Tapenade",
    "Arancini",
    "Pesto Pasta",
    "Mediterranean Chickpea Salad",
    "Greek Spinach Pie",
    "Artichoke Hearts",
    "Panzanella Salad",
    "Mediterranean Grilled Vegetables",
  ],
  mexican: [
    "Mexican",
    "Burritos",
    "Birria",
    "Sopapillas",
    "Posole",
    "Tacos",
    "Al Pastor",
    "Carnitas",
    "Barbacoa",
    "Fish Tacos",
    "Birria Tacos",
    "Guacamole",
    "Quesadillas",
    "Enchiladas",
    "Salsa",
    "Pico de Gallo",
    "Salsa Verde",
    "Salsa Roja",
    "Burritos",
    "Tamales",
    "Chiles Rellenos",
    "Churros",
    "Mole",
    "Pozole",
    "Nachos",
    "Queso Fundido",
    "Ceviche",
    "Flautas",
    "Tostadas",
    "Gorditas",
    "Huaraches",
    "Elote (Mexican Street Corn)",
    "Molletes",
    "Camarones a la Diabla",
    "Cochinita Pibil",
    "Sopes",
    "Aguachile",
    "Campechana",
    "Tlayudas",
    "Sopes",
    "Pan Dulce (Sweet Bread)",
    "Horchata",
    "Tepache (Fermented Pineapple Drink)",
    "Michelada",
  ],
  middle_eastern: [
    "Middle Eastern",
    "Shawarma",
    "Falafel",
    "Hummus",
    "Baba Ganoush",
    "Kebabs",
    "Shish Kebab",
    "Adana Kebab",
    "Tabbouleh",
    "Fattoush",
    "Dolma",
    "Kibbeh",
    "Manakish",
    "Labneh",
    "Mutabbal",
    "Fatayer",
    "Stuffed Grape Leaves",
    "Shawarma Poutine",
    "Shish Taouk",
    "Sambousek",
    "Sfiha",
    "Shish Barak",
    "Moutabal",
    "Chicken Kabsa",
    "Ful Medames",
    "Makloubeh",
    "Halva",
    "Arabic Coffee (Gahwa)",
    "Baklava",
    "Maqluba",
    "Harira Soup",
    "Mhammar",
    "Sabich",
    "Shanklish",
    "Malooga",
    "Mezze Platter",
    "Arabic Sweets",
    "Basbousa",
    "Atayef",
    "Katayef",
    "Warbat",
    "Ma'amoul",
  ],
  moroccan: [
    "Moroccan",
    "Couscous",
    "Tagine",
    "Chicken Tagine",
    "Lamb Tagine",
    "Vegetable Tagine",
    "Harira Soup",
    "Bastilla",
    "Kefta",
    "Pastilla",
    "Mechoui",
    "Rfissa",
    "Zaalouk",
    "Shakshuka",
    "B'stilla",
    "Mrouzia",
    "Briouat",
    "Harcha",
    "Baghrir (Thousand Hole Pancakes)",
    "Makouda",
    "Maakouda",
    "Msemen",
    "Sellou",
    "Chermoula",
    "Zaalouk",
    "Khobz",
    "M'hanncha",
    "Amlou",
    "Chebakia",
    "Mrouzia",
    "Hout Quari",
    "Loubia",
    "Sfenj (Moroccan Doughnuts)",
    "Rghaif",
    "Kefta Mkaouara",
    "Chakhchoukha",
    "Marqa",
    "Fish Chermoula",
    "Moroccan Mint Tea",
    "Amlou",
    "Rfissa",
    "Seffa",
    "Bissara",
    "Zaalouk",
    "Batbout",
    "Harira Soup",
    "Baghrir",
    "Harcha",
  ],
  nepali: ["Nepali", "Momos", "Dal Bhat", "Sel Roti"],
  nigerian: [
    "Nigerian",
    "Jollof rice",
    "Pounded yam and egusi soup",
    "Zobo",
    "Fufu",
    "Eba",
  ],
  north_african: [
    "North African",
    "Couscous",
    "Tagine",
    "Chicken Tagine",
    "Lamb Tagine",
    "Vegetable Tagine",
    "Harira Soup",
    "Shakshuka",
    "Bastilla",
    "Mechoui",
    "Rfissa",
    "Zaalouk",
    "Chermoula",
    "Mrouzia",
    "Brik",
    "Msemen",
    "Khobz",
    "Lablabi",
    "Bissara",
    "Tunisian Couscous",
    "Jwaz (Lamb Stew)",
    "Berkoukes",
    "Makroudh",
    "Baghrir (Thousand Hole Pancakes)",
    "Harissa",
    "Maghrebi Mint Tea",
    "Lablabi (Chickpea Soup)",
    "Tajine Zitoune (Olive Tagine)",
    "Tabil (Spice Blend)",
    "Mhamsa (Steamed Wheat)",
    "Ghoriba",
    "Tunisian Mechouia",
    "Tunisian Fish Stew",
    "Merguez Sausages",
    "Chakchouka",
    "Kaak",
    "Chakalaka",
  ],
  pakistani: [
    "Pakistani",
    "Biryani",
    "Nihari",
    "Haleem",
    "Seekh Kebabs",
    "Chapli Kebabs",
    "Chicken Karahi",
    "Aloo Keema (Minced Meat with Potatoes)",
    "Saag (Mustard Greens)",
    "Pakoras",
    "Samosas",
    "Chaat",
    "Peshawari Naan",
    "Rogan Josh",
    "Chicken Tikka",
    "Daal Chawal (Lentils with Rice)",
    "Paya Curry (Trotters Curry)",
    "Korma",
    "Jalebi",
    "Gulab Jamun",
    "Peshawari Ice Cream (Kulfi)",
  ],
  palestinian: ["Palestinian", "Musakhan", "Maqluba"],
  "pan-african": [
    "Pan-African",
    "Afro-Caribbean cuisine",
    "Afro-Latin cuisine",
    "Jollof Rice",
    "Fufu and Soup",
    "Bobotie",
    "Doro Wat",
    "Bunny Chow",
    "Moambe Chicken",
    "Maafe",
    "Akara",
    "Injera",
    "Piri Piri Chicken",
    "Nyama Choma",
    "Plantain and Beans",
    "Egusi Soup",
    "Sadza",
    "Couscous",
    "Braai (Barbecue)",
    "Biltong",
    "Kapenta",
    "Pounded Yam and Egusi Soup",
    "Pap en Vleis_Shisa Nyama",
    "Moin Moin",
    "Sukuma Wiki",
    "Chakalaka",
    "Chura",
    "Efo Riro",
    "Tsebhi Birsen",
    "Samak Tibs",
    "Piri Piri Prawns",
    "Atayef",
    "Ceebu Jen",
    "Mtori",
    "Dibi",
    "Kachumbari",
    "Plasas",
    "Cachupa",
    "Nkatenkwan",
    "Domoda",
    "Koshari",
    "Akoho sy Voanio",
    "Mafé",
    "Isidudu",
    "Kapenta with Sadza",
    "Fata",
  ],
  persian: [
    "Persian",
    "Chelo Kebab",
    "Ghormeh Sabzi",
    "Fesenjan",
    "Zereshk Polo",
    "Tahchin",
    "Kashk-e Bademjan",
    "Dolmeh",
    "Ash Reshteh",
    "Khoresh-e Gheimeh",
    "Joojeh Kebab",
    "Baghali Polo",
    "Mirza Ghasemi",
    "Abgoosht",
    "Adas Polo",
    "Sabzi Polo",
    "Kotlet",
    "Kuku Sabzi",
    "Halim",
    "Morasa Polo",
    "Asheh Mast",
    "Baghali Ghatogh",
    "Shirin Polo",
    "Saffron Ice Cream (Bastani Sonnati)",
    "Doogh",
    "Ash-e Anar",
    "Zulbia and Bamieh",
    "Sholeh Zard",
    "Yazdi Cake",
    "Sohan Asali",
    "Gaz",
    "Samanu",
    "Gondi",
    "Sheer Khurma",
    "Persian Tea",
  ],
  peruvian: [
    "Peruvian",
    "Ceviche",
    "Lomo Saltado",
    "Aji de Gallina",
    "Causa",
    "Anticuchos",
    "Rocoto Relleno",
    "Tacu Tacu",
    "Papa a la Huancaina",
    "Tiradito",
    "Seco de Res",
    "Arroz con Pollo",
    "Pollo a la Brasa",
    "Chupe de Camarones",
    "Ceviche de Conchas Negras",
    "Escabeche de Pescado",
    "Olluquito con Charqui",
    "Carapulcra",
    "Chupe de Gallina",
    "Pachamanca",
    "Huancaina Sauce",
    "Cuy al Horno",
    "Picarones",
    "Mazamorra Morada",
    "Suspiro a la Limena",
    "Alfajores",
    "Inca Kola (Soft Drink)",
    "Chicha Morada",
    "Pisco Sour",
    "Choclo con Queso",
    "Butifarra Sandwich",
    "Yuquitas Fritas",
    "Tequeños",
    "Camote Glaseado",
    "Maracuya Sour",
    "Aji Amarillo",
  ],
  pizza: [
    "Pizza",
    "Margherita",
    "Pepperoni",
    "Supreme",
    "Hawaiian Pizza",
    "Meat Lovers Pizza",
    "Veggie Pizza",
    "BBQ Chicken Pizza",
    "Buffalo Chicken Pizza",
    "White Pizza",
    "Mediterranean Pizza",
    "Pesto Chicken Pizza",
    "Supreme Pizza",
    "Four Cheese Pizza",
    "Neapolitan Pizza",
    "Sicilian Pizza",
    "Chicago Deep Dish Pizza",
    "Calzone",
    "Stromboli",
    "Margherita Flatbread",
    "Prosciutto and Arugula Pizza",
    "Capricciosa Pizza",
    "Quattro Formaggi Pizza",
    "Truffle Mushroom Pizza",
    "Sausage and Mushroom Pizza",
    "Spinach and Feta Pizza",
    "Artichoke and Spinach Pizza",
    "Chicken Alfredo Pizza",
    "Bacon and Egg Breakfast Pizza",
    "Fig and Prosciutto Pizza",
    "Shrimp Scampi Pizza",
    "Tandoori Chicken Pizza",
    "Pastrami Reuben Pizza",
    "Philly Cheesesteak Pizza",
    "BLT Pizza",
    "Mediterranean Veggie Flatbread",
    "Buffalo Cauliflower Pizza",
    "Vegan Margherita Pizza",
    "Gluten-Free Pizza",
  ],
  portuguese: ["Portuguese", "Bacalhau", "Pastéis de nata"],
  puerto_rican: [
    "Puerto Rican",
    "Mofongo",
    "Pernil",
    "Tostones",
    "Pastelón",
    "Alcapurrias",
    "Ropa Vieja",
    "Bacalaitos",
    "Coquito",
    "Pionono",
    "Mamposteao",
    "Pernil Asado",
    "Jibarito",
    "Empanadillas",
    "Sorullitos",
    "Tembleque",
    "Sancocho",
    "Piñón",
    "Pollo Guisado",
    "Yuca al Mojo",
    "Mondongo",
    "Arroz con Pollo",
    "Pitorro (Moonshine)",
    "Guineítos en Escabeche",
    "Chicharrón de Pollo",
    "Habichuelas Guisadas",
    "Yautía Fritters",
    "Pollo al Horno",
    "Besitos de Coco",
    "Quesitos",
    "Arroz con Dulce",
    "Morcilla",
    "Pique",
    "Guava Pastries",
    "Ensalada de Carrucho (Conch Salad)",
    "Canoa (Sweet Plantain Boat)",
    "Malanga Fritters",
    "Mojito Isleno",
    "Arroz con gandules",
  ],
  ramen: [
    "Ramen",
    "Shoyu ramen",
    "Miso ramen",
    "Tonkotsu ramen",
    "Vegetarian ramen",
  ],
  raw_bar: [
    "Raw Bar",
    "Seafood platter",
    "Oysters on the Half Shell",
    "Shrimp Cocktail",
    "Clams",
    "Lobster Tail",
    "Crab Legs",
    "Ceviche",
    "Tuna Tartare",
    "Seafood Tower",
    "Mussels",
    "Octopus Carpaccio",
    "Scallop Crudo",
    "Smoked Salmon",
    "Sashimi Platter",
    "Sea Urchin",
    "Razor Clams",
    "Conch",
    "Peruvian Tiradito",
    "Poke Bowl",
    "Chilled Crab Claw",
    "Oyster Shooters",
    "Lobster Carpaccio",
    "Seafood Ceviche",
    "Marinated Anchovies",
    "Fresh Seafood Platter",
    "King Crab Legs",
    "Cherrystone Clams",
    "Bay Scallops",
    "Crab Claws with Mustard Sauce",
    "Mediterranean Seafood Salad",
    "Tuna Poke Tostadas",
    "Lobster Salad",
    "Oyster Po' Boy",
    "Clam Strips",
    "Seafood Pasta Salad",
    "Smoked Oyster Dip",
    "Snow Crab Clusters",
    "Pickled Herring",
    "Seafood Crudités",
    "Shrimp and Avocado Salad",
  ],
  romanian: ["Romanian", "Mămăligă", "Sarmale", "Mici"],
  russian: [
    "Russian",
    "Borscht",
    "Pelmeni",
    "Beef Stroganoff",
    "Borscht",
    "Pelmeni (Dumplings)",
    "Beef Stroganoff",
    "Blini (Russian Pancakes)",
    "Piroshki (Stuffed Pastries)",
    "Golubtsy (Cabbage Rolls)",
    "Olivier Salad",
    "Shchi (",
    "Selyodka Pod Shuboy",
    "Rasstegai",
    "Kulebyaka",
    "Plov",
    "Solyanka",
    "Syrniki",
    "Kvass",
    "Tvorog",
    "Medovik",
    "Draniki",
    "Zapekanka",
  ],
  salads: [
    "Salads",
    "Caesar salad",
    "Greek Salad",
    "Caprese Salad",
    "Cobb Salad",
    "Waldorf Salad",
    "Spinach and Strawberry Salad",
    "Nicoise Salad",
    "Chicken Caesar Salad",
    "Asian Chicken Salad",
    "Mediterranean Salad",
    "Quinoa Salad",
    "Kale and Avocado Salad",
    "Tuna Salad",
    "Pear and Gorgonzola Salad",
    "Roasted Vegetable Salad",
  ],
  salvadoran: ["Salvadoran", "Pupusas", "Yuca con chicharrón", "Ensalada"],
  sandwiches: [
    "Sandwiches",
    "Sub sandwiches",
    "Panini",
    "Gourmet sandwiches",
    "​BLT (Bacon Lettuce, Tomato)",
    "Club Sandwich",
    "Reuben Sandwich",
    "Turkey and Swiss Sandwich",
    "Grilled Cheese Sandwich",
    "Philly Cheesesteak",
    "Cuban Sandwich",
    "Tuna Salad Sandwich",
    "Chicken Club Sandwich",
    "Egg Salad Sandwich",
    "Italian Submarine Sandwich",
    "Banh Mi",
    "Po' Boy Sandwich",
    "Caprese Sandwich",
    "Chicken Parmesan Sandwich",
    "French Dip Sandwich",
    "Meatball Sub",
    "Pulled Pork Sandwich",
    "Smoked Salmon Bagel Sandwich",
    "Veggie Wrap",
  ],
  scandinavian: ["Scandinavian", "Smørrebrød", "Gravad lax", "Koldskål"],
  seafood: [
    "Seafood",
    "Seafood platter",
    "Grilled fish",
    "Seafood boil",
    "Lobster Bisque",
    "Shrimp Scampi",
    "Clam Chowder",
    "Grilled Salmon",
    "Fish Tacos",
    "Crab Cakes",
    "Seafood Paella",
    "Oysters Rockefeller",
    "Tuna Poke Bowl",
    "Cioppino",
    "Lobster Roll",
    "Fried Calamari",
    "Garlic Butter Shrimp",
    "Coconut Shrimp",
    "Bouillabaisse",
    "Steamed Mussels",
    "Ceviche",
    "Smoked Salmon Bagel",
    "Scallops in Garlic Butter",
    "Fish and Chips",
  ],
  senegalese: ["Senegalese", "Thieboudienne", "Mafé", "Dakar street food"],
  serbian: ["Serbian", "Ćevapi", "Sarma", "Pljeskavica"],
  singaporean: [
    "Singaporean",
    "Hainanese Chicken Rice",
    "Laksa",
    "Char Kway Teow",
    "Chili Crab",
    "Hokkien Mee",
    "Nasi Lemak",
    "Satay",
    "Bak Kut Teh",
    "Rojak",
    "Kaya Toast",
    "Chicken Satay",
    "Nasi Goreng",
    "Mee Goreng",
    "Otak-Otak",
    "Fish Head Curry",
    "Hokkaido-Style Hot Pot (Steamboat)",
    "Nonya Kueh",
    "Oyster Omelette",
    "Curry Puff",
    "Murtabak",
    "Hainanese Beef Noodles",
    "Hokkien Char Mee",
    "Mee Siam",
    "Wanton Mee",
    "Chicken Rice Balls",
    "Popiah",
    "Roti Prata",
    "Ice Kachang",
    "Chilli Crab Bao",
    "Laksa Pizza",
    "Chilli Crab Pasta",
    "Kaya Croissant",
    "Char Kway Teow Burger",
    "Satay Skewers",
    "Hainanese Chicken Rice Burger",
    "Laksa Fried Chicken",
    "Hokkien Mee Tacos",
    "Durian Ice Cream",
    "Pandan Cake",
    "Kopi Tarik",
  ],
  somali: ["Somali", "Suqaar", "Sambusa", "Canjeero"],
  soul_food: [
    "Soul Food",
    "Fried Chicken",
    "Collard Greens",
    "Macaroni and Cheese",
    "Cornbread",
    "Black-Eyed Peas",
    "Fried Catfish",
    "Gumbo",
    "Jambalaya",
    "Biscuits and Gravy",
    "Shrimp and Grits",
    "Hushpuppies",
    "Red Beans and Rice",
    "Chicken and Waffles",
    "Fried Okra",
    "Peach Cobbler",
    "Sweet Potato Pie",
    "Candied Yams",
    "Cornbread Stuffing",
    "BBQ Ribs",
    "Chitlins",
    "Crawfish Etouffee",
    "Pecan Pie",
    "Watermelon Salad",
    "Smothered Pork Chops",
    "Banana Pudding",
    "Grits",
    "Collard Greens with Ham Hocks",
    "Blackened Catfish",
    "Buttermilk Biscuits",
    "Pork and Beans",
    "Country Fried Steak",
    "Hoppin' John",
    "Sweet Tea",
    "Corn Fritters",
    "Candied Sweet Potatoes",
    "Southern Fried Chicken",
    "Sausage Gravy",
    "Buttered Corn",
    "Cornmeal Mush",
    "Chicken Fried Steak",
    "Pickled Okra",
    "Spicy Fried Chicken",
    "Boiled Peanuts",
    "Sweet Potato Casserole",
  ],
  south_african: [
    "South African",
    "Bobotie",
    "Bunny Chow",
    "Boerewors",
    "Biltong",
    "Malva Pudding",
    "Potjiekos",
    "Koeksisters",
    "Amarula Don Pedro",
    "Boerewors Roll",
    "Chakalaka",
    "Milk Tart",
    "Braai (Barbecue)",
    "Droë Wors",
    "Samoosas",
    "Vetkoek",
    "Pap and Wors",
    "Bunny Chow",
    "Waterblommetjie Bredie",
    "Monkey Gland Sauce",
    "Tomato Bredie",
    "Snoek",
    "Cape Malay Curry",
    "Durban Curry",
    "Vetkoek and Mince",
    "Sosaties",
    "Melktert",
    "Roosterkoek",
    "Amarula Malva Pudding",
    "Potbrood",
    "Pampoenkoekies",
    "Umngqusho",
    "Bokkoms",
    "Amarula Ice Cream",
    "Peri-Peri Chicken",
    "Denningvleis",
    "Mosbolletjies",
    "Amarula Coffee",
    "Peppermint Crisp Tart",
    "Amarula Milk Tart",
    "Chicken Bunny Chow",
    "Bunny Chow with Lamb Curry",
    "Vetkoek with Boerewors",
    "Potjiekos with Oxtail",
    "Koeksisters with Rooibos Glaze",
    "Malva Pudding Ice Cream",
    "Bunny Chow Sliders",
    "Bobotie Spring Rolls",
    "Rooibos Malva Pudding",
    "Lamb Potjie with Waterblommetjies",
    "Samp and Beans",
    "Umngqusho with Butternut Squash",
    "Denningvleis Tacos",
    "Peri-Peri Prawns",
    "Boerewors and Pap Pizza",
    "Milk Tart Cupcakes",
    "Chakalaka Dip",
    "Vetkoek with Apricot Jam",
  ],
  southeast_asian: [
    "Southeast Asian",
    "Pad Thai",
    "Pho",
    "Satay",
    "Nasi Goreng",
    "Tom Yum",
    "Banh Mi",
    "Som Tum",
    "Laksa",
    "Rendang",
    "Spring Rolls",
    "Hainanese Chicken Rice",
    "Mi Quang",
    "Green Curry",
    "Balut",
    "Mango Sticky Rice",
    "Char Kway Teow",
    "Durian",
  ],
  southern: [
    "Southern",
    "Fried catfish",
    "Soul Food",
    "Fried Chicken",
    "Biscuits and Gravy",
    "Grits",
    "Collard Greens",
    "Cornbread",
    "Shrimp and Grits",
    "Chicken and Waffles",
    "Pulled Pork Barbecue",
    "Hushpuppies",
    "Fried Green Tomatoes",
    "Catfish",
    "Jambalaya",
    "Red Beans and Rice",
    "Pecan Pie",
    "Shrimp Etouffee",
    "Corn Pudding",
    "Banana Pudding",
    "Sweet Tea",
  ],
  spanish: [
    "Spanish",
    "Paella",
    "Tapas",
    "Patatas Bravas",
    "Gambas al Ajillo (Garlic Shrimp)",
    "Jamón Ibérico",
    "Chorizo a la Sidra",
    "Boquerones",
    "Pimientos de Padrón",
    "Croquetas",
    "Pulpo a la Gallega (Galician Octopus)",
    "Gazpacho",
    "Tortilla Española",
    "Churros with Chocolate",
    "Pan con Tomate",
    "Albondigas (Meatballs)",
    "Calamares a la Romana",
    "Bacalao a la Vizcaína (Basque-Style Cod)",
    "Pescado a la Sal (Salt-Baked Fish)",
    "Flan",
    "Pisto",
    "Salmorejo",
    "Fabada Asturiana",
    "Escudella i Carn d'Olla (Catalan Stew)",
    "Gambas a la Plancha (Grilled Prawns)",
    "Cochinillo Asado (Roast Suckling Pig)",
    "Empanada Gallega",
    "Bunuelos",
    "Ensaladilla Rusa",
    "Tarta de Santiago",
    "Crema Catalana",
    "Cava",
    "Sangria",
    "Cured Meats",
    "Chorizo",
    "Salchichón",
    "Lomo Embuchado",
    "Manchego Cheese",
    "Grilled Sardines",
    "Sobrasada",
    "Escargot",
    "Tapenade",
    "White Anchovies (Boquerones en Vinagre)",
    "Turrón",
    "Piquillos Rellenos de Marisco (Seafood-Stuffed Piquillo Peppers)",
    "Tarta de Queso (Cheesecake)",
    "Cava Sangria",
    "Spanish Omelette",
    "Pulpo a la Brasa (Grilled Octopus)",
    "Caracoles (Snails)",
    "Chuletas de Cordero (Lamb Chops)",
    "Ensalada de Pulpo (Octopus Salad)",
    "Queso de Cabra al Horno (Baked Goat Cheese)",
    "Gambas al Pil Pil",
    "Crema de Calabaza",
  ],
  sri_lankan: ["Sri Lankan", "Kottu Roti", "Hoppers"],
  steakhouse: [
    "Steakhouse",
    "Ribeye",
    "Filet mignon",
    "Porterhouse",
    "Grilled steaks",
    "Steak marinades",
    "Steak rubs",
    "Prime rib",
    "Hanger Steak",
    "Skirt Steak",
    "Steak",
    "Shrimp Cocktail",
    "Lobster Tail",
    "Crab Legs",
    "Blue Cheese Wedge Salad",
    "Lobster Bisque",
    "French Onion Soup",
    "Filet Mignon Sliders",
    "Beef Tenderloin Tips",
    "Surf and Turf",
    "Porterhouse Steak for Two",
    "Dry-Aged Steak",
    "Wagyu Steak",
    "Kobe Beef",
  ],
  syrian: ["Syrian", "Kibbeh", "Fatteh", "Fattoush"],
  sushi: [
    "Sushi",
    "Nigiri",
    "Sashimi",
    "Roll combinations",
    "Poke Bowl",
    "Sushi Burrito",
    "Narezushi",
    "Maki Rolls",
    "California Roll",
    "Spicy Tuna Roll",
    "Dragon Roll",
    "Rainbow Roll",
    "Philadelphia Roll",
  ],
  swedish: [
    "Swedish",
    "Swedish meatballs",
    "Gravlax",
    "Köttbullar",
    "Gravad lax",
    "Smörgåsbord",
    "Räksmörgås",
    "Surströmming",
    "Janssons frestelse",
    "Pyttipanna",
    "Kanelbullar",
    "Sill och Potatis",
    "Gravlaxsås",
    "Pitepalt",
    "Knäckebröd",
    "Silltallrik",
    "Ärtsoppa",
    "Falukorv",
    "Smörgåstårta",
    "Ostkaka",
  ],
  taiwanese: [
    "Taiwanese",
    "Bubble Tea",
    "Gua Bao",
    "Taiwanese noodle soup",
    "Boba",
  ],
  tapas: [
    "Tapas",
    "Patatas Bravas",
    "Gambas al Ajillo (Garlic Shrimp)",
    "Chorizo a la Sidra (Chorizo in Cider)",
    "Albondigas (Meatballs)",
    "Pimientos de Padron (Padron Peppers)",
    "Tortilla Española (Spanish Omelette)",
    "Jamón Ibérico",
    "Pan con Tomate (Tomato Bread)",
    "Queso Manchego (Manchego Cheese)",
    "Boquerones en Vinagre (Marinated Anchovies)",
    "Croquetas",
    "Pulpo a la Gallega (Galician-Style Octopus)",
    "Gambas a la Plancha (Grilled Prawns)",
    "Pinchos Morunos (Grilled Meat Skewers)",
    "Calamares a la Romana (Fried Squid)",
    "Escudella i Carn d'Olla",
  ],
  texan: [
    "Texan",
    "Queso",
    "Fajitas",
    "Chili con carne",
    "Texas barbecue",
    "Chicken fried steak",
    "Texan chili",
    "Tex mex",
  ],
  thai: [
    "Thai",
    "Tom Yum",
    "Tom Yum Goong (Spicy Shrimp Soup)",
    "Tom Yum Gai (Spicy Chicken Soup)",
    "Green Curry",
    "Green Chicken Curry",
    "Green Beef Curry",
    "Green Vegetable Curry",
    "Pad Thai",
    "Traditional Pad Thai",
    "Shrimp Pad Thai",
    "Chicken Pad Thai",
    "Tofu Pad Thai",
    "Som Tum",
    "Som Tum Thai (Green Papaya Salad)",
    "Som Tum Mamuang (Green Mango Salad)",
    "Pineapple Fried Rice",
    "Coconut Soup",
    "Tom Kha Gai (Chicken Coconut Soup)",
    "Tom Kha Tofu (Tofu Coconut Soup)",
    "Massaman Curry",
    "Massaman Beef Curry",
    "Massaman Chicken Curry",
    "Massaman Vegetable Curry",
    "Red Curry",
    "Red Chicken Curry",
    "Red Beef Curry",
    "Red Vegetable Curry",
    "Pad See Ew",
    "Chicken Pad See Ew",
    "Beef Pad See Ew",
    "Tofu Pad See Ew",
    "Khao Soi",
    "Chicken Khao Soi",
    "Beef Khao Soi",
    "Tofu Khao Soi",
    "Spring Rolls",
    "Chicken Spring Rolls",
    "Shrimp Spring Rolls",
    "Vegetarian Spring Rolls",
    "Satay",
    "Chicken Satay",
    "Beef Satay",
    "Tofu Satay",
    "Mango Sticky Rice",
    "Thai Iced Tea",
    "Pad Kra Pao",
    "Chicken Pad Kra Pao",
    "Beef Pad Kra Pao",
    "Tofu Pad Kra Pao",
    "Tom Klong Pla",
    "Tom Klong Pla Kem (Spicy Smoked Fish Soup)",
    "Yum Woon Sen",
    "Yum Woon Sen Goong (Glass Noodle Salad with Shrimp)",
    "Kao Niew Mamuang",
    "Kao Niew Mamuang (Mango with Sticky Rice)",
    "Khao Pad",
    "Chicken Khao Pad (Fried Rice)",
    "Shrimp Khao Pad (Fried Rice)",
    "Vegetable Khao Pad (Fried Rice)",
    "Panang Curry",
    "Panang Chicken Curry",
    "Panang Beef Curry",
    "Panang Vegetable Curry",
  ],
  tibetan: ["Tibetan", "Momos", "Thukpa", "Butter tea"],
  trinidadian: ["Trinidadian", "Doubles", "Callaloo", "Roti"],
  turkish: ["Turkish", "Kebabs", "Meze", "Baklava"],
  uruguayan: ["Uruguayan", "Asado", "Chivito", "Milanesa"],
  uyghur: ["Uyghur", "Laghman", "Polo", "Samsa"],
  uzbek: ["Uzbek", "Plov", "Shashlik", "Manti"],
  vegan: [
    "Vegan",
    "Plant-based cuisine",
    "Vegan desserts",
    "Vegan comfort food",
  ],
  vegetarian: [
    "Vegetarian",
    "Plant-based cuisine",
    "Vegetarian pasta",
    "Vegan options",
  ],
  venezuelan: ["Venezuelan", "Arepas", "Pabellón Criollo"],
  vietnamese: [
    "Vietnamese",
    "Pho",
    "Banh Mi",
    "Goi Cuon",
    "Bun Cha",
    "Com Tam",
    "Bun Bo Hue",
    "Ca Kho To",
    "Cha Ca Thang Long",
    "Banh Xeo",
    "Mi Quang",
    "Bo Luc Lac",
    "Nom Hoa Chuoi",
    "Hu Tieu",
    "Banh Cuon",
    "Cao Lau",
    "Che",
  ],
  west_african: [
    "West African",
    "Jollof rice",
    "Egusi Soup",
    "Pounded Yam and Egusi Soup",
    "Suya",
    "Akara",
    "Moi Moi",
    "Chinchinga",
    "Banga Soup",
    "Puff-Puff",
    "Sesame Seed Soup (Ogbono Soup)",
    "Sokara",
    "Amala and Ewedu Soup",
    "Dodo",
  ],
};

/**
 * Cuisine types mapped to some arbitrary ID to be referenced by other entities such as
 * Taste Profiles. Important: The ids these cuisines are mapped to should not be changed beyond this point because other
 * unrelated entities directly reference these values and will not know if they change unexpectedly
 */
export const SupportedCuisines = {
  afghan: 0,
  algerian: 1,
  american: 2,
  argentinian: 3,
  armenian: 4,
  australian: 5,
  austrian: 6,
  bbq: 7,
  bakery_cafe: 8,
  balkan: 9,
  bangladeshi: 10,
  bar_wine_bar: 11,
  bengali: 12,
  bhutanese: 13,
  brazilian: 14,
  breakfast: 15,
  british: 16,
  burmese: 17,
  cajun: 18,
  cambodian: 19,
  canadian: 20,
  caribbean: 21,
  chinese: 22,
  chino_latino: 23,
  colombian: 24,
  creole: 25,
  cuban: 26,
  czech: 27,
  diner: 28,
  dominican: 29,
  deli: 30,
  dessert: 31,
  eastern_european: 32,
  ecuadorian: 33,
  egyptian: 34,
  ethiopian: 35,
  european: 36,
  fast_food: 37,
  filipino: 38,
  french: 39,
  fried_chicken: 40,
  georgian: 41,
  german: 42,
  greek: 43,
  guyanese: 44,
  haitian: 45,
  hawaiian: 46,
  honduran: 47,
  hot_dogs: 48,
  hot_pot: 49,
  hungarian: 50,
  ice_cream: 51,
  indian: 52,
  indonesian: 53,
  israeli: 54,
  italian: 55,
  jamaican: 56,
  japanese: 57,
  jewish: 58,
  jordanian: 59,
  korean: 60,
  "laos_(lao)": 61,
  latin: 62,
  lebanese: 63,
  malaysian: 64,
  mediterranean: 65,
  mexican: 66,
  middle_eastern: 67,
  moroccan: 68,
  nepali: 69,
  nigerian: 70,
  north_african: 71,
  pakistani: 72,
  palestinian: 73,
  "pan-african": 74,
  persian: 75,
  peruvian: 76,
  pizza: 77,
  portuguese: 78,
  puerto_rican: 79,
  ramen: 80,
  raw_bar: 81,
  romanian: 82,
  russian: 83,
  salads: 84,
  salvadoran: 85,
  sandwiches: 86,
  scandinavian: 87,
  seafood: 88,
  senegalese: 89,
  serbian: 90,
  singaporean: 91,
  somali: 92,
  soul_food: 93,
  south_african: 94,
  southeast_asian: 95,
  southern: 96,
  spanish: 97,
  sri_lankan: 98,
  steakhouse: 99,
  syrian: 100,
  sushi: 101,
  swedish: 102,
  taiwanese: 103,
  tapas: 104,
  texan: 105,
  thai: 106,
  tibetan: 107,
  trinidadian: 108,
  turkish: 109,
  uruguayan: 110,
  uyghur: 111,
  uzbek: 112,
  vegan: 113,
  vegetarian: 114,
  venezuelan: 115,
  vietnamese: 116,
  west_african: 117,
};

// Cuisine Icon Image URLs
// The corresponding icon image in URL form for each cuisine type, Note: Do make sure these files are actually present on the CDN
export const SupportedCuisineImageURLs = {
  afghan: "https://cdn.foncii.com/static-assets/cuisine-icons/afghan.jpg",
  algerian: "https://cdn.foncii.com/static-assets/cuisine-icons/algerian.jpg",
  american: "https://cdn.foncii.com/static-assets/cuisine-icons/american.jpg",
  argentinian:
    "https://cdn.foncii.com/static-assets/cuisine-icons/argentinian.jpg",
  armenian: "https://cdn.foncii.com/static-assets/cuisine-icons/armenian.jpg",
  australian:
    "https://cdn.foncii.com/static-assets/cuisine-icons/australian.jpg",
  austrian: "https://cdn.foncii.com/static-assets/cuisine-icons/austrian.jpg",
  bbq: "https://cdn.foncii.com/static-assets/cuisine-icons/bbq.jpg",
  bakery_cafe:
    "https://cdn.foncii.com/static-assets/cuisine-icons/bakery_cafe.jpg",
  balkan: "https://cdn.foncii.com/static-assets/cuisine-icons/balkan.jpg",
  bangladeshi:
    "https://cdn.foncii.com/static-assets/cuisine-icons/bangladeshi.jpg",
  bar_wine_bar:
    "https://cdn.foncii.com/static-assets/cuisine-icons/bar_wine_bar.jpg",
  bengali: "https://cdn.foncii.com/static-assets/cuisine-icons/bengali.jpg",
  bhutanese: "https://cdn.foncii.com/static-assets/cuisine-icons/bhutanese.jpg",
  brazilian: "https://cdn.foncii.com/static-assets/cuisine-icons/brazilian.jpg",
  breakfast: "https://cdn.foncii.com/static-assets/cuisine-icons/breakfast.jpg",
  british: "https://cdn.foncii.com/static-assets/cuisine-icons/british.jpg",
  burmese: "https://cdn.foncii.com/static-assets/cuisine-icons/burmese.jpg",
  cajun: "https://cdn.foncii.com/static-assets/cuisine-icons/cajun.jpg",
  cambodian: "https://cdn.foncii.com/static-assets/cuisine-icons/cambodian.jpg",
  canadian: "https://cdn.foncii.com/static-assets/cuisine-icons/canadian.jpg",
  caribbean: "https://cdn.foncii.com/static-assets/cuisine-icons/caribbean.jpg",
  chinese: "https://cdn.foncii.com/static-assets/cuisine-icons/chinese.jpg",
  chino_latino:
    "https://cdn.foncii.com/static-assets/cuisine-icons/chino_latino.jpg",
  colombian: "https://cdn.foncii.com/static-assets/cuisine-icons/colombian.jpg",
  creole: "https://cdn.foncii.com/static-assets/cuisine-icons/creole.jpg",
  cuban: "https://cdn.foncii.com/static-assets/cuisine-icons/cuban.jpg",
  czech: "https://cdn.foncii.com/static-assets/cuisine-icons/czech.jpg",
  diner: "https://cdn.foncii.com/static-assets/cuisine-icons/diner.jpg",
  dominican: "https://cdn.foncii.com/static-assets/cuisine-icons/dominican.jpg",
  deli: "https://cdn.foncii.com/static-assets/cuisine-icons/deli.jpg",
  dessert: "https://cdn.foncii.com/static-assets/cuisine-icons/dessert.jpg",
  eastern_european:
    "https://cdn.foncii.com/static-assets/cuisine-icons/eastern_european.jpg",
  ecuadorian:
    "https://cdn.foncii.com/static-assets/cuisine-icons/ecuadorian.jpg",
  egyptian: "https://cdn.foncii.com/static-assets/cuisine-icons/egyptian.jpg",
  ethiopian: "https://cdn.foncii.com/static-assets/cuisine-icons/ethiopian.jpg",
  european: "https://cdn.foncii.com/static-assets/cuisine-icons/european.jpg",
  fast_food: "https://cdn.foncii.com/static-assets/cuisine-icons/fast_food.jpg",
  filipino: "https://cdn.foncii.com/static-assets/cuisine-icons/filipino.jpg",
  french: "https://cdn.foncii.com/static-assets/cuisine-icons/french.jpg",
  fried_chicken:
    "https://cdn.foncii.com/static-assets/cuisine-icons/fried_chicken.jpg",
  georgian: "https://cdn.foncii.com/static-assets/cuisine-icons/georgian.jpg",
  german: "https://cdn.foncii.com/static-assets/cuisine-icons/german.jpg",
  greek: "https://cdn.foncii.com/static-assets/cuisine-icons/greek.jpg",
  guyanese: "https://cdn.foncii.com/static-assets/cuisine-icons/guyanese.jpg",
  haitian: "https://cdn.foncii.com/static-assets/cuisine-icons/haitian.jpg",
  hawaiian: "https://cdn.foncii.com/static-assets/cuisine-icons/hawaiian.jpg",
  honduran: "https://cdn.foncii.com/static-assets/cuisine-icons/honduran.jpg",
  hot_dogs: "https://cdn.foncii.com/static-assets/cuisine-icons/hot_dogs.jpg",
  hot_pot: "https://cdn.foncii.com/static-assets/cuisine-icons/hot_pot.jpg",
  hungarian: "https://cdn.foncii.com/static-assets/cuisine-icons/hungarian.jpg",
  ice_cream: "https://cdn.foncii.com/static-assets/cuisine-icons/ice_cream.jpg",
  indian: "https://cdn.foncii.com/static-assets/cuisine-icons/indian.jpg",
  indonesian:
    "https://cdn.foncii.com/static-assets/cuisine-icons/indonesian.jpg",
  israeli: "https://cdn.foncii.com/static-assets/cuisine-icons/israeli.jpg",
  italian: "https://cdn.foncii.com/static-assets/cuisine-icons/italian.jpg",
  jamaican: "https://cdn.foncii.com/static-assets/cuisine-icons/jamaican.jpg",
  japanese: "https://cdn.foncii.com/static-assets/cuisine-icons/japanese.jpg",
  jewish: "https://cdn.foncii.com/static-assets/cuisine-icons/jewish.jpg",
  jordanian: "https://cdn.foncii.com/static-assets/cuisine-icons/jordanian.jpg",
  korean: "https://cdn.foncii.com/static-assets/cuisine-icons/korean.jpg",
  "laos_(lao)":
    "https://cdn.foncii.com/static-assets/cuisine-icons/laos_(lao).jpg",
  latin: "https://cdn.foncii.com/static-assets/cuisine-icons/latin.jpg",
  lebanese: "https://cdn.foncii.com/static-assets/cuisine-icons/lebanese.jpg",
  malaysian: "https://cdn.foncii.com/static-assets/cuisine-icons/malaysian.jpg",
  mediterranean:
    "https://cdn.foncii.com/static-assets/cuisine-icons/mediterranean.jpg",
  mexican: "https://cdn.foncii.com/static-assets/cuisine-icons/mexican.jpg",
  middle_eastern:
    "https://cdn.foncii.com/static-assets/cuisine-icons/middle_eastern.jpg",
  moroccan: "https://cdn.foncii.com/static-assets/cuisine-icons/moroccan.jpg",
  nepali: "https://cdn.foncii.com/static-assets/cuisine-icons/nepali.jpg",
  nigerian: "https://cdn.foncii.com/static-assets/cuisine-icons/nigerian.jpg",
  north_african:
    "https://cdn.foncii.com/static-assets/cuisine-icons/north_african.jpg",
  pakistani: "https://cdn.foncii.com/static-assets/cuisine-icons/pakistani.jpg",
  palestinian:
    "https://cdn.foncii.com/static-assets/cuisine-icons/palestinian.jpg",
  "pan-african":
    "https://cdn.foncii.com/static-assets/cuisine-icons/pan-african.jpg",
  persian: "https://cdn.foncii.com/static-assets/cuisine-icons/persian.jpg",
  peruvian: "https://cdn.foncii.com/static-assets/cuisine-icons/peruvian.jpg",
  pizza: "https://cdn.foncii.com/static-assets/cuisine-icons/pizza.jpg",
  portuguese:
    "https://cdn.foncii.com/static-assets/cuisine-icons/portuguese.jpg",
  puerto_rican:
    "https://cdn.foncii.com/static-assets/cuisine-icons/puerto_rican.jpg",
  ramen: "https://cdn.foncii.com/static-assets/cuisine-icons/ramen.jpg",
  raw_bar: "https://cdn.foncii.com/static-assets/cuisine-icons/raw_bar.jpg",
  romanian: "https://cdn.foncii.com/static-assets/cuisine-icons/romanian.jpg",
  russian: "https://cdn.foncii.com/static-assets/cuisine-icons/russian.jpg",
  salads: "https://cdn.foncii.com/static-assets/cuisine-icons/salads.jpg",
  salvadoran:
    "https://cdn.foncii.com/static-assets/cuisine-icons/salvadoran.jpg",
  sandwiches:
    "https://cdn.foncii.com/static-assets/cuisine-icons/sandwiches.jpg",
  scandinavian:
    "https://cdn.foncii.com/static-assets/cuisine-icons/scandinavian.jpg",
  seafood: "https://cdn.foncii.com/static-assets/cuisine-icons/seafood.jpg",
  senegalese:
    "https://cdn.foncii.com/static-assets/cuisine-icons/senegalese.jpg",
  serbian: "https://cdn.foncii.com/static-assets/cuisine-icons/serbian.jpg",
  singaporean:
    "https://cdn.foncii.com/static-assets/cuisine-icons/singaporean.jpg",
  somali: "https://cdn.foncii.com/static-assets/cuisine-icons/somali.jpg",
  soul_food: "https://cdn.foncii.com/static-assets/cuisine-icons/soul_food.jpg",
  south_african:
    "https://cdn.foncii.com/static-assets/cuisine-icons/south_african.jpg",
  southeast_asian:
    "https://cdn.foncii.com/static-assets/cuisine-icons/southeast_asian.jpg",
  southern: "https://cdn.foncii.com/static-assets/cuisine-icons/southern.jpg",
  spanish: "https://cdn.foncii.com/static-assets/cuisine-icons/spanish.jpg",
  sri_lankan:
    "https://cdn.foncii.com/static-assets/cuisine-icons/sri_lankan.jpg",
  steakhouse:
    "https://cdn.foncii.com/static-assets/cuisine-icons/steakhouse.jpg",
  syrian: "https://cdn.foncii.com/static-assets/cuisine-icons/syrian.jpg",
  sushi: "https://cdn.foncii.com/static-assets/cuisine-icons/sushi.jpg",
  swedish: "https://cdn.foncii.com/static-assets/cuisine-icons/swedish.jpg",
  taiwanese: "https://cdn.foncii.com/static-assets/cuisine-icons/taiwanese.jpg",
  tapas: "https://cdn.foncii.com/static-assets/cuisine-icons/tapas.jpg",
  texan: "https://cdn.foncii.com/static-assets/cuisine-icons/texan.jpg",
  thai: "https://cdn.foncii.com/static-assets/cuisine-icons/thai.jpg",
  tibetan: "https://cdn.foncii.com/static-assets/cuisine-icons/tibetan.jpg",
  trinidadian:
    "https://cdn.foncii.com/static-assets/cuisine-icons/trinidadian.jpg",
  turkish: "https://cdn.foncii.com/static-assets/cuisine-icons/turkish.jpg",
  uruguayan: "https://cdn.foncii.com/static-assets/cuisine-icons/uruguayan.jpg",
  uyghur: "https://cdn.foncii.com/static-assets/cuisine-icons/uyghur.jpg",
  uzbek: "https://cdn.foncii.com/static-assets/cuisine-icons/uzbek.jpg",
  vegan: "https://cdn.foncii.com/static-assets/cuisine-icons/vegan.jpg",
  vegetarian:
    "https://cdn.foncii.com/static-assets/cuisine-icons/vegetarian.jpg",
  venezuelan:
    "https://cdn.foncii.com/static-assets/cuisine-icons/venezuelan.jpg",
  vietnamese:
    "https://cdn.foncii.com/static-assets/cuisine-icons/vietnamese.jpg",
  west_african:
    "https://cdn.foncii.com/static-assets/cuisine-icons/west_african.jpg",
};

// Supported Localizations
export const LocalizedCuisineNames = {
  english: {
    afghan: "Afghan",
    algerian: "Algerian",
    american: "American",
    argentinian: "Argentinian",
    armenian: "Armenian",
    australian: "Australian",
    austrian: "Austrian",
    bbq: "BBQ",
    bakery_cafe: "Bakery/Cafe",
    balkan: "Balkan",
    bangladeshi: "Bangladeshi",
    bar_wine_bar: "Bar/Wine Bar",
    bengali: "Bengali",
    bhutanese: "Bhutanese",
    brazilian: "Brazilian",
    breakfast: "Breakfast",
    british: "British",
    burmese: "Burmese",
    cajun: "Cajun",
    cambodian: "Cambodian",
    canadian: "Canadian",
    caribbean: "Caribbean",
    chinese: "Chinese",
    chino_latino: "Chino Latino",
    colombian: "Colombian",
    creole: "Creole",
    cuban: "Cuban",
    czech: "Czech",
    diner: "Diner",
    dominican: "Dominican",
    deli: "Deli",
    dessert: "Dessert",
    eastern_european: "Eastern European",
    ecuadorian: "Ecuadorian",
    egyptian: "Egyptian",
    ethiopian: "Ethiopian",
    european: "European",
    fast_food: "Fast Food",
    filipino: "Filipino",
    french: "French",
    fried_chicken: "Fried Chicken",
    georgian: "Georgian",
    german: "German",
    greek: "Greek",
    guyanese: "Guyanese",
    haitian: "Haitian",
    hawaiian: "Hawaiian",
    honduran: "Honduran",
    hot_dogs: "Hot Dogs",
    hot_pot: "Hot Pot",
    hungarian: "Hungarian",
    ice_cream: "Ice Cream",
    indian: "Indian",
    indonesian: "Indonesian",
    israeli: "Israeli",
    italian: "Italian",
    jamaican: "Jamaican",
    japanese: "Japanese",
    jewish: "Jewish",
    jordanian: "Jordanian",
    korean: "Korean",
    "laos_(lao)": "Laos (Lao)",
    latin: "Latin",
    lebanese: "Lebanese",
    malaysian: "Malaysian",
    mediterranean: "Mediterranean",
    mexican: "Mexican",
    middle_eastern: "Middle Eastern",
    moroccan: "Moroccan",
    nepali: "Nepali",
    nigerian: "Nigerian",
    north_african: "North African",
    pakistani: "Pakistani",
    palestinian: "Palestinian",
    "pan-african": "Pan-African",
    persian: "Persian",
    peruvian: "Peruvian",
    pizza: "Pizza",
    portuguese: "Portuguese",
    puerto_rican: "Puerto Rican",
    ramen: "Ramen",
    raw_bar: "Raw Bar",
    romanian: "Romanian",
    russian: "Russian",
    salads: "Salads",
    salvadoran: "Salvadoran",
    sandwiches: "Sandwiches",
    scandinavian: "Scandinavian",
    seafood: "Seafood",
    senegalese: "Senegalese",
    serbian: "Serbian",
    singaporean: "Singaporean",
    somali: "Somali",
    soul_food: "Soul Food",
    south_african: "South African",
    southeast_asian: "Southeast Asian",
    southern: "Southern",
    spanish: "Spanish",
    sri_lankan: "Sri Lankan",
    steakhouse: "Steakhouse",
    syrian: "Syrian",
    sushi: "Sushi",
    swedish: "Swedish",
    taiwanese: "Taiwanese",
    tapas: "Tapas",
    texan: "Texan",
    thai: "Thai",
    tibetan: "Tibetan",
    trinidadian: "Trinidadian",
    turkish: "Turkish",
    uruguayan: "Uruguayan",
    uyghur: "Uyghur",
    uzbek: "Uzbek",
    vegan: "Vegan",
    vegetarian: "Vegetarian",
    venezuelan: "Venezuelan",
    vietnamese: "Vietnamese",
    west_african: "West African",
  },
};
